//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.RadScheduler {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RadScheduler.Main", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todo el dia.
        /// </summary>
        internal static string AdvancedAllDayEvent {
            get {
                return ResourceManager.GetString("AdvancedAllDayEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string AdvancedCalendarCancel {
            get {
                return ResourceManager.GetString("AdvancedCalendarCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string AdvancedCalendarOK {
            get {
                return ResourceManager.GetString("AdvancedCalendarOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoy.
        /// </summary>
        internal static string AdvancedCalendarToday {
            get {
                return ResourceManager.GetString("AdvancedCalendarToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        internal static string AdvancedClose {
            get {
                return ResourceManager.GetString("AdvancedClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diariamente.
        /// </summary>
        internal static string AdvancedDaily {
            get {
                return ResourceManager.GetString("AdvancedDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dia.
        /// </summary>
        internal static string AdvancedDay {
            get {
                return ResourceManager.GetString("AdvancedDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dia(s).
        /// </summary>
        internal static string AdvancedDays {
            get {
                return ResourceManager.GetString("AdvancedDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripcion.
        /// </summary>
        internal static string AdvancedDescription {
            get {
                return ResourceManager.GetString("AdvancedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realizada.
        /// </summary>
        internal static string AdvancedDone {
            get {
                return ResourceManager.GetString("AdvancedDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edita.
        /// </summary>
        internal static string AdvancedEditAppointment {
            get {
                return ResourceManager.GetString("AdvancedEditAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminar en.
        /// </summary>
        internal static string AdvancedEndAfter {
            get {
                return ResourceManager.GetString("AdvancedEndAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar por.
        /// </summary>
        internal static string AdvancedEndByThisDate {
            get {
                return ResourceManager.GetString("AdvancedEndByThisDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de fin obligatoria.
        /// </summary>
        internal static string AdvancedEndDateRequired {
            get {
                return ResourceManager.GetString("AdvancedEndDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo final obligatoria.
        /// </summary>
        internal static string AdvancedEndTimeRequired {
            get {
                return ResourceManager.GetString("AdvancedEndTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los dias.
        /// </summary>
        internal static string AdvancedEvery {
            get {
                return ResourceManager.GetString("AdvancedEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los fines de semana.
        /// </summary>
        internal static string AdvancedEveryWeekday {
            get {
                return ResourceManager.GetString("AdvancedEveryWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primer.
        /// </summary>
        internal static string AdvancedFirst {
            get {
                return ResourceManager.GetString("AdvancedFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuarto.
        /// </summary>
        internal static string AdvancedFourth {
            get {
                return ResourceManager.GetString("AdvancedFourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        internal static string AdvancedFrom {
            get {
                return ResourceManager.GetString("AdvancedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cada Hora.
        /// </summary>
        internal static string AdvancedHourly {
            get {
                return ResourceManager.GetString("AdvancedHourly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora(s).
        /// </summary>
        internal static string AdvancedHours {
            get {
                return ResourceManager.GetString("AdvancedHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero Invalido.
        /// </summary>
        internal static string AdvancedInvalidNumber {
            get {
                return ResourceManager.GetString("AdvancedInvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultimo.
        /// </summary>
        internal static string AdvancedLast {
            get {
                return ResourceManager.GetString("AdvancedLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dia.
        /// </summary>
        internal static string AdvancedMaskDay {
            get {
                return ResourceManager.GetString("AdvancedMaskDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin de semana.
        /// </summary>
        internal static string AdvancedMaskWeekday {
            get {
                return ResourceManager.GetString("AdvancedMaskWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dia de Fin de semana.
        /// </summary>
        internal static string AdvancedMaskWeekendDay {
            get {
                return ResourceManager.GetString("AdvancedMaskWeekendDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menusal.
        /// </summary>
        internal static string AdvancedMonthly {
            get {
                return ResourceManager.GetString("AdvancedMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes(es).
        /// </summary>
        internal static string AdvancedMonths {
            get {
                return ResourceManager.GetString("AdvancedMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mas detalles.
        /// </summary>
        internal static string AdvancedMoreDetails {
            get {
                return ResourceManager.GetString("AdvancedMoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Pogramacion.
        /// </summary>
        internal static string AdvancedNewAppointment {
            get {
                return ResourceManager.GetString("AdvancedNewAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No termina.
        /// </summary>
        internal static string AdvancedNoEndDate {
            get {
                return ResourceManager.GetString("AdvancedNoEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ocurrencias.
        /// </summary>
        internal static string AdvancedOccurrences {
            get {
                return ResourceManager.GetString("AdvancedOccurrences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de.
        /// </summary>
        internal static string AdvancedOf {
            get {
                return ResourceManager.GetString("AdvancedOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de cada.
        /// </summary>
        internal static string AdvancedOfEvery {
            get {
                return ResourceManager.GetString("AdvancedOfEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rango de ocurrencias.
        /// </summary>
        internal static string AdvancedRange {
            get {
                return ResourceManager.GetString("AdvancedRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repetir cada.
        /// </summary>
        internal static string AdvancedRecurEvery {
            get {
                return ResourceManager.GetString("AdvancedRecurEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetir.
        /// </summary>
        internal static string AdvancedRecurrence {
            get {
                return ResourceManager.GetString("AdvancedRecurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tarea Recurrente.
        /// </summary>
        internal static string AdvancedRecurringAppointment {
            get {
                return ResourceManager.GetString("AdvancedRecurringAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset exceptions.
        /// </summary>
        internal static string AdvancedReset {
            get {
                return ResourceManager.GetString("AdvancedReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        internal static string AdvancedSecond {
            get {
                return ResourceManager.GetString("AdvancedSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date is required.
        /// </summary>
        internal static string AdvancedStartDateRequired {
            get {
                return ResourceManager.GetString("AdvancedStartDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time must be before end time.
        /// </summary>
        internal static string AdvancedStartTimeBeforeEndTime {
            get {
                return ResourceManager.GetString("AdvancedStartTimeBeforeEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time is required.
        /// </summary>
        internal static string AdvancedStartTimeRequired {
            get {
                return ResourceManager.GetString("AdvancedStartTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asunto.
        /// </summary>
        internal static string AdvancedSubject {
            get {
                return ResourceManager.GetString("AdvancedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide appointment subject.
        /// </summary>
        internal static string AdvancedSubjectRequired {
            get {
                return ResourceManager.GetString("AdvancedSubjectRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to el.
        /// </summary>
        internal static string AdvancedThe {
            get {
                return ResourceManager.GetString("AdvancedThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tercer.
        /// </summary>
        internal static string AdvancedThird {
            get {
                return ResourceManager.GetString("AdvancedThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Final.
        /// </summary>
        internal static string AdvancedTo {
            get {
                return ResourceManager.GetString("AdvancedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semanal.
        /// </summary>
        internal static string AdvancedWeekly {
            get {
                return ResourceManager.GetString("AdvancedWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week(s) on.
        /// </summary>
        internal static string AdvancedWeeks {
            get {
                return ResourceManager.GetString("AdvancedWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabajando....
        /// </summary>
        internal static string AdvancedWorking {
            get {
                return ResourceManager.GetString("AdvancedWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anual.
        /// </summary>
        internal static string AdvancedYearly {
            get {
                return ResourceManager.GetString("AdvancedYearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todo el dia.
        /// </summary>
        internal static string AllDay {
            get {
                return ResourceManager.GetString("AllDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancealr.
        /// </summary>
        internal static string ConfirmCancel {
            get {
                return ResourceManager.GetString("ConfirmCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta seguro de borrar le registro?.
        /// </summary>
        internal static string ConfirmDeleteText {
            get {
                return ResourceManager.GetString("ConfirmDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar borrar.
        /// </summary>
        internal static string ConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ConfirmOK {
            get {
                return ResourceManager.GetString("ConfirmOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete only this occurrence..
        /// </summary>
        internal static string ConfirmRecurrenceDeleteOccurrence {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceDeleteOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the series..
        /// </summary>
        internal static string ConfirmRecurrenceDeleteSeries {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceDeleteSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting a recurring appointment.
        /// </summary>
        internal static string ConfirmRecurrenceDeleteTitle {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit only this occurrence..
        /// </summary>
        internal static string ConfirmRecurrenceEditOccurrence {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceEditOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the series..
        /// </summary>
        internal static string ConfirmRecurrenceEditSeries {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceEditSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing a recurring appointment.
        /// </summary>
        internal static string ConfirmRecurrenceEditTitle {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move only this occurrence..
        /// </summary>
        internal static string ConfirmRecurrenceMoveOccurrence {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceMoveOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the series..
        /// </summary>
        internal static string ConfirmRecurrenceMoveSeries {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceMoveSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving a recurring appointment.
        /// </summary>
        internal static string ConfirmRecurrenceMoveTitle {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceMoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize only this occurrence..
        /// </summary>
        internal static string ConfirmRecurrenceResizeOccurrence {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceResizeOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize the series..
        /// </summary>
        internal static string ConfirmRecurrenceResizeSeries {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceResizeSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resizing a recurring appointment.
        /// </summary>
        internal static string ConfirmRecurrenceResizeTitle {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceResizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete all existing recurrence exceptions?.
        /// </summary>
        internal static string ConfirmResetExceptionsText {
            get {
                return ResourceManager.GetString("ConfirmResetExceptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm reset exceptions.
        /// </summary>
        internal static string ConfirmResetExceptionsTitle {
            get {
                return ResourceManager.GetString("ConfirmResetExceptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Appointment.
        /// </summary>
        internal static string ContextMenuAddAppointment {
            get {
                return ResourceManager.GetString("ContextMenuAddAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Recurring Appointment.
        /// </summary>
        internal static string ContextMenuAddRecurringAppointment {
            get {
                return ResourceManager.GetString("ContextMenuAddRecurringAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        internal static string ContextMenuDelete {
            get {
                return ResourceManager.GetString("ContextMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string ContextMenuEdit {
            get {
                return ResourceManager.GetString("ContextMenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ir al dia.
        /// </summary>
        internal static string ContextMenuGoToToday {
            get {
                return ResourceManager.GetString("ContextMenuGoToToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dia.
        /// </summary>
        internal static string HeaderDay {
            get {
                return ResourceManager.GetString("HeaderDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes.
        /// </summary>
        internal static string HeaderMonth {
            get {
                return ResourceManager.GetString("HeaderMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varios Dias.
        /// </summary>
        internal static string HeaderMultiDay {
            get {
                return ResourceManager.GetString("HeaderMultiDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguiente Dia.
        /// </summary>
        internal static string HeaderNextDay {
            get {
                return ResourceManager.GetString("HeaderNextDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dia anterior.
        /// </summary>
        internal static string HeaderPrevDay {
            get {
                return ResourceManager.GetString("HeaderPrevDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linea de tiempo.
        /// </summary>
        internal static string HeaderTimeline {
            get {
                return ResourceManager.GetString("HeaderTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoy.
        /// </summary>
        internal static string HeaderToday {
            get {
                return ResourceManager.GetString("HeaderToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semana.
        /// </summary>
        internal static string HeaderWeek {
            get {
                return ResourceManager.GetString("HeaderWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordar.
        /// </summary>
        internal static string Reminder {
            get {
                return ResourceManager.GetString("Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to before start.
        /// </summary>
        internal static string ReminderBeforeStart {
            get {
                return ResourceManager.GetString("ReminderBeforeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dia.
        /// </summary>
        internal static string ReminderDay {
            get {
                return ResourceManager.GetString("ReminderDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dias.
        /// </summary>
        internal static string ReminderDays {
            get {
                return ResourceManager.GetString("ReminderDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        internal static string ReminderDismiss {
            get {
                return ResourceManager.GetString("ReminderDismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss All.
        /// </summary>
        internal static string ReminderDismissAll {
            get {
                return ResourceManager.GetString("ReminderDismissAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to due in.
        /// </summary>
        internal static string ReminderDueIn {
            get {
                return ResourceManager.GetString("ReminderDueIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hora.
        /// </summary>
        internal static string ReminderHour {
            get {
                return ResourceManager.GetString("ReminderHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to horas.
        /// </summary>
        internal static string ReminderHours {
            get {
                return ResourceManager.GetString("ReminderHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minuto.
        /// </summary>
        internal static string ReminderMinute {
            get {
                return ResourceManager.GetString("ReminderMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutos.
        /// </summary>
        internal static string ReminderMinutes {
            get {
                return ResourceManager.GetString("ReminderMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ninguno.
        /// </summary>
        internal static string ReminderNone {
            get {
                return ResourceManager.GetString("ReminderNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir.
        /// </summary>
        internal static string ReminderOpenItem {
            get {
                return ResourceManager.GetString("ReminderOpenItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overdue.
        /// </summary>
        internal static string ReminderOverdue {
            get {
                return ResourceManager.GetString("ReminderOverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordar.
        /// </summary>
        internal static string Reminders {
            get {
                return ResourceManager.GetString("Reminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snooze.
        /// </summary>
        internal static string ReminderSnooze {
            get {
                return ResourceManager.GetString("ReminderSnooze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Snooze to be reminded again in:.
        /// </summary>
        internal static string ReminderSnoozeHint {
            get {
                return ResourceManager.GetString("ReminderSnoozeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semana.
        /// </summary>
        internal static string ReminderWeek {
            get {
                return ResourceManager.GetString("ReminderWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semanas.
        /// </summary>
        internal static string ReminderWeeks {
            get {
                return ResourceManager.GetString("ReminderWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do not remove this key..
        /// </summary>
        internal static string ReservedResource {
            get {
                return ResourceManager.GetString("ReservedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show 24 hours....
        /// </summary>
        internal static string Show24Hours {
            get {
                return ResourceManager.GetString("Show24Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opciones.
        /// </summary>
        internal static string ShowAdvancedForm {
            get {
                return ResourceManager.GetString("ShowAdvancedForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horario Laboral.
        /// </summary>
        internal static string ShowBusinessHours {
            get {
                return ResourceManager.GetString("ShowBusinessHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mas.
        /// </summary>
        internal static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
    }
}
