//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class accesorio
    {
        public int cod_accesorio { get; set; }
        public string nombre_accesorio { get; set; }
        public int cod_linea { get; set; }
        public string ind_1 { get; set; }
        public string ind_2 { get; set; }
    
        public virtual linea linea { get; set; }
    }
}
