//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class accion_novedad
    {
        public accion_novedad()
        {
            this.novedad_movimiento = new HashSet<novedad_movimiento>();
        }
    
        public int cod_accion_novedad { get; set; }
        public string nombre_accion_novedad { get; set; }
        public Nullable<int> cod_tipo_novedad { get; set; }
    
        public virtual ICollection<novedad_movimiento> novedad_movimiento { get; set; }
    }
}
