//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class accion_seguir_cientifica
    {
        public accion_seguir_cientifica()
        {
            this.accion_seguirxasesoria_cientifica = new HashSet<accion_seguirxasesoria_cientifica>();
            this.accion_seguirxseguimiento_cientifica = new HashSet<accion_seguirxseguimiento_cientifica>();
        }
    
        public int cod_accion_seguir_cientifica { get; set; }
        public string nombre_accion_seguir { get; set; }
        public Nullable<bool> ind_qc { get; set; }
        public Nullable<bool> ind_visita { get; set; }
    
        public virtual ICollection<accion_seguirxasesoria_cientifica> accion_seguirxasesoria_cientifica { get; set; }
        public virtual ICollection<accion_seguirxseguimiento_cientifica> accion_seguirxseguimiento_cientifica { get; set; }
    }
}
