//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class adjunto_contrato_suministro
    {
        public int cod_adjunto_contrato_suministro { get; set; }
        public int cod_tipo_adjunto_contrato_suministro { get; set; }
        public int cod_contratos_suministro { get; set; }
        public string nombre_archivo { get; set; }
        public byte[] archivo { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> cod_estado_adjunto_contrato_suministro { get; set; }
        public Nullable<System.DateTime> fecha_aprobacion_cartera { get; set; }
        public Nullable<System.DateTime> fecha_aprobacion_juridico { get; set; }
        public Nullable<System.DateTime> fecha_aprobacion_inicial { get; set; }
        public Nullable<int> aprobacion_cartera_por { get; set; }
        public Nullable<int> aprobacion_juridico_por { get; set; }
        public Nullable<int> aprobacion_inicial_por { get; set; }
    
        public virtual contratos_suministro contratos_suministro { get; set; }
        public virtual estado_adjunto_contrato_suministro estado_adjunto_contrato_suministro { get; set; }
        public virtual tipo_adjunto_contrato_suministro tipo_adjunto_contrato_suministro { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
        public virtual usuario usuario2 { get; set; }
    }
}
