//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class archivo_template_revision_equipo
    {
        public int cod_archivo_template_revision_equipo { get; set; }
        public int cod_revision_equipos { get; set; }
        public byte[] archivo { get; set; }
        public System.DateTime ultima_modificacion { get; set; }
        public int modificado_por { get; set; }
        public string nombre_archivo { get; set; }
    
        public virtual revision_equipos revision_equipos { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
