//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class asistente_capacitacion
    {
        public int cod_capacitacion { get; set; }
        public int cod_usuario { get; set; }
        public byte[] adj_asistencia { get; set; }
        public byte[] adj_certificado { get; set; }
        public byte[] adj_evaluacion { get; set; }
        public Nullable<bool> aprobo { get; set; }
        public string extension_asistencia { get; set; }
        public string extension_certificado { get; set; }
        public string extension_evaluacion { get; set; }
    
        public virtual capacitacion capacitacion { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
