//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class campos_template_revision
    {
        public int cod_campos_template_revision { get; set; }
        public Nullable<int> cod_template_revison_equipo { get; set; }
        public string campo { get; set; }
        public Nullable<int> fila { get; set; }
        public Nullable<int> columna { get; set; }
        public Nullable<bool> esBoleano { get; set; }
        public Nullable<bool> esNegado { get; set; }
    
        public virtual template_revison_equipo template_revison_equipo { get; set; }
    }
}
