//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cgq_query
    {
        public cgq_query()
        {
            this.cgq_layout_pivote = new HashSet<cgq_layout_pivote>();
            this.cgq_parametrosquery = new HashSet<cgq_parametrosquery>();
            this.cgq_queryxgrupo_usuario = new HashSet<cgq_queryxgrupo_usuario>();
            this.cgq_queryxusuario = new HashSet<cgq_queryxusuario>();
            this.cgq_tablas_pivote = new HashSet<cgq_tablas_pivote>();
        }
    
        public int cod_query { get; set; }
        public string nombre_query { get; set; }
        public string sentencia_sql { get; set; }
        public Nullable<bool> empiezo_con_columnas { get; set; }
        public Nullable<System.DateTime> ultima_fecha_generacion { get; set; }
        public Nullable<bool> filtra_fecha { get; set; }
        public Nullable<int> cod_linea { get; set; }
        public Nullable<bool> es_pivote { get; set; }
        public Nullable<int> cod_origen_datos { get; set; }
        public string campo_fecha { get; set; }
        public Nullable<int> periodo_inicial { get; set; }
        public Nullable<bool> generar_tabla_auxiliar { get; set; }
        public Nullable<bool> generar_grafica { get; set; }
        public string tipo_grafica { get; set; }
        public Nullable<bool> limpia_tabla_auxiliar { get; set; }
        public string columna_agregado { get; set; }
        public string agregado { get; set; }
    
        public virtual ICollection<cgq_layout_pivote> cgq_layout_pivote { get; set; }
        public virtual ICollection<cgq_parametrosquery> cgq_parametrosquery { get; set; }
        public virtual linea linea { get; set; }
        public virtual origen_datos origen_datos { get; set; }
        public virtual ICollection<cgq_queryxgrupo_usuario> cgq_queryxgrupo_usuario { get; set; }
        public virtual ICollection<cgq_queryxusuario> cgq_queryxusuario { get; set; }
        public virtual ICollection<cgq_tablas_pivote> cgq_tablas_pivote { get; set; }
    }
}
