//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cgq_tablas_pivote
    {
        public int cod_cgq_tablas_pivote { get; set; }
        public string campo { get; set; }
        public string caption { get; set; }
        public Nullable<int> cod_query { get; set; }
        public Nullable<bool> es_columna { get; set; }
        public Nullable<bool> es_fila { get; set; }
    
        public virtual cgq_query cgq_query { get; set; }
    }
}
