//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ciudad
    {
        public ciudad()
        {
            this.bodega = new HashSet<bodega>();
            this.movimiento = new HashSet<movimiento>();
            this.sucursal_cliente = new HashSet<sucursal_cliente>();
            this.transportador = new HashSet<transportador>();
        }
    
        public int cod_ciudad { get; set; }
        public Nullable<int> cod_departamento { get; set; }
        public string nombre_ciudad { get; set; }
        public string cod_manual { get; set; }
    
        public virtual ICollection<bodega> bodega { get; set; }
        public virtual departamento departamento { get; set; }
        public virtual ICollection<movimiento> movimiento { get; set; }
        public virtual ICollection<sucursal_cliente> sucursal_cliente { get; set; }
        public virtual ICollection<transportador> transportador { get; set; }
    }
}
