//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ciudades
    {
        public ciudades()
        {
            this.contratos_suministro = new HashSet<contratos_suministro>();
            this.OrdenPrestamo = new HashSet<OrdenPrestamo>();
            this.regionesXusuarios = new HashSet<regionesXusuarios>();
            this.sucursalCliente = new HashSet<sucursalCliente>();
        }
    
        public string codPais { get; set; }
        public string codDepartamento { get; set; }
        public string codCiudad { get; set; }
        public string nombreCiudad { get; set; }
    
        public virtual departamentos departamentos { get; set; }
        public virtual ICollection<contratos_suministro> contratos_suministro { get; set; }
        public virtual ICollection<OrdenPrestamo> OrdenPrestamo { get; set; }
        public virtual ICollection<regionesXusuarios> regionesXusuarios { get; set; }
        public virtual ICollection<sucursalCliente> sucursalCliente { get; set; }
    }
}
