//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes
    {
        public clientes()
        {
            this.contactosClientes = new HashSet<contactosClientes>();
            this.contrato_consumo = new HashSet<contrato_consumo>();
            this.solicitudServicio = new HashSet<solicitudServicio>();
            this.sucursalCliente = new HashSet<sucursalCliente>();
        }
    
        public string nitCliente { get; set; }
        public string nombreCliente { get; set; }
        public byte[] logotipo { get; set; }
        public string nombreContactoPrincipal { get; set; }
        public string apellidosContacto { get; set; }
        public string docContacto { get; set; }
        public string codTipoDoc { get; set; }
        public string tituloContacto { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
        public string fax { get; set; }
        public string celular { get; set; }
        public string email { get; set; }
        public string numeroSocio { get; set; }
        public Nullable<bool> esLocal { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual tipoDocumento tipoDocumento { get; set; }
        public virtual tituloContacto tituloContacto1 { get; set; }
        public virtual ICollection<contactosClientes> contactosClientes { get; set; }
        public virtual ICollection<contrato_consumo> contrato_consumo { get; set; }
        public virtual ICollection<solicitudServicio> solicitudServicio { get; set; }
        public virtual ICollection<sucursalCliente> sucursalCliente { get; set; }
    }
}
