//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public cliente()
        {
            this.contacto_cliente = new HashSet<contacto_cliente>();
            this.detalle_movimiento = new HashSet<detalle_movimiento>();
            this.existencia = new HashSet<existencia>();
            this.sucursal_cliente = new HashSet<sucursal_cliente>();
        }
    
        public int cod_cliente { get; set; }
        public Nullable<int> cod_linea { get; set; }
        public string nombre_cliente { get; set; }
        public Nullable<int> cod_tipo_documento { get; set; }
        public string documento { get; set; }
        public string representante_cliente { get; set; }
        public string email { get; set; }
        public Nullable<bool> ind_inactivo { get; set; }
        public Nullable<bool> ind_nacional { get; set; }
        public Nullable<bool> ind_1 { get; set; }
        public Nullable<bool> ind_2 { get; set; }
        public string documento_adicional { get; set; }
        public string codigo_manual { get; set; }
        public byte[] logo { get; set; }
    
        public virtual ICollection<contacto_cliente> contacto_cliente { get; set; }
        public virtual ICollection<detalle_movimiento> detalle_movimiento { get; set; }
        public virtual ICollection<existencia> existencia { get; set; }
        public virtual ICollection<sucursal_cliente> sucursal_cliente { get; set; }
    }
}
