//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class componente
    {
        public componente()
        {
            this.ArchivosxComponente = new HashSet<ArchivosxComponente>();
            this.Modelos = new HashSet<Modelos>();
        }
    
        public string codFabricante { get; set; }
        public string codComponente { get; set; }
        public string nombreComponente { get; set; }
        public Nullable<int> frecuenciaMantenimiento { get; set; }
        public string codtipoComponente { get; set; }
        public string codSubTipoComponente { get; set; }
        public string codsubCategoriaCom { get; set; }
        public byte[] fotografia { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<ArchivosxComponente> ArchivosxComponente { get; set; }
        public virtual subCategoriaComponente subCategoriaComponente { get; set; }
        public virtual ICollection<Modelos> Modelos { get; set; }
    }
}
