//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumoContratoxLinea
    {
        public string numeroContrato { get; set; }
        public string codGrupoLineaConsumo { get; set; }
        public string codLinea { get; set; }
        public Nullable<int> codGrupo { get; set; }
        public Nullable<decimal> montoConsumo { get; set; }
    
        public virtual lineasConsumo lineasConsumo { get; set; }
    }
}
