//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class contratosxEquipo
    {
        public contratosxEquipo()
        {
            this.mantenimientosxContrato1 = new HashSet<mantenimientosxContrato>();
        }
    
        public string serial { get; set; }
        public int codOtroSi { get; set; }
        public string numeroContrato { get; set; }
        public Nullable<int> mantenimientosRealizados { get; set; }
        public Nullable<int> mantenimientosxContrato { get; set; }
        public Nullable<bool> esActivo { get; set; }
        public Nullable<int> correctivos { get; set; }
        public Nullable<int> preventivos { get; set; }
        public int codContratosxEquipo { get; set; }
    
        public virtual contratos contratos { get; set; }
        public virtual equipos equipos { get; set; }
        public virtual ICollection<mantenimientosxContrato> mantenimientosxContrato1 { get; set; }
    }
}
