//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class contratos_suministro
    {
        public contratos_suministro()
        {
            this.adjunto_contrato_suministro = new HashSet<adjunto_contrato_suministro>();
            this.archivoxcontratos_suministro = new HashSet<archivoxcontratos_suministro>();
            this.divisionxcontrato_suministro = new HashSet<divisionxcontrato_suministro>();
            this.estampillas_contrato_sumisnistro = new HashSet<estampillas_contrato_sumisnistro>();
            this.grupo_reactivoxcontrato_suministro = new HashSet<grupo_reactivoxcontrato_suministro>();
            this.log_cambios_estado_contratos_suministro = new HashSet<log_cambios_estado_contratos_suministro>();
            this.polizas_contrato_suministro = new HashSet<polizas_contrato_suministro>();
            this.producto_experiencia_contratoxcontrato_conmsumo = new HashSet<producto_experiencia_contratoxcontrato_conmsumo>();
        }
    
        public int cod_contratos_suministro { get; set; }
        public string numero_contrato { get; set; }
        public int cod_usuario_asesor { get; set; }
        public int cod_estado_contrato_suministro { get; set; }
        public string consecutivo_interno { get; set; }
        public string nitCliente { get; set; }
        public string codContacto { get; set; }
        public string direccion_envio_contrato { get; set; }
        public string codPais_envio_contrato { get; set; }
        public string codDepartamento_envio_contrato { get; set; }
        public string codCiudad_envio_contrato { get; set; }
        public string contacto_juridico { get; set; }
        public string numero_celular_contacto_juridico { get; set; }
        public System.DateTime fecha_incio { get; set; }
        public System.DateTime fecha_terminacion { get; set; }
        public decimal valor_contrato { get; set; }
        public string otrosi { get; set; }
        public Nullable<System.DateTime> fecha_otro_si { get; set; }
        public string numero_contrato_vinculado { get; set; }
        public string observaciones { get; set; }
        public Nullable<bool> aplica_estampilla { get; set; }
        public Nullable<bool> aplica_polizas { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string codSucursal { get; set; }
        public Nullable<bool> es_contrato { get; set; }
        public Nullable<bool> es_orden_compra { get; set; }
        public Nullable<bool> no_genera_flujo { get; set; }
        public Nullable<bool> incluye_apoyo_tecnologico { get; set; }
        public Nullable<bool> genera_multa { get; set; }
        public Nullable<System.DateTime> fecha_limite_legalizacion { get; set; }
        public Nullable<int> codAsesor { get; set; }
        public string contrato_apoyo { get; set; }
        public Nullable<int> cod_motivo_anulacion_suministro { get; set; }
        public Nullable<System.DateTime> fecha_anulacion { get; set; }
        public Nullable<int> anulada_por { get; set; }
        public string observaciones_anulacion { get; set; }
    
        public virtual ICollection<adjunto_contrato_suministro> adjunto_contrato_suministro { get; set; }
        public virtual ICollection<archivoxcontratos_suministro> archivoxcontratos_suministro { get; set; }
        public virtual asesoresComerciales asesoresComerciales { get; set; }
        public virtual ciudades ciudades { get; set; }
        public virtual contactosClientes contactosClientes { get; set; }
        public virtual estado_contrato_suministro estado_contrato_suministro { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual ICollection<divisionxcontrato_suministro> divisionxcontrato_suministro { get; set; }
        public virtual ICollection<estampillas_contrato_sumisnistro> estampillas_contrato_sumisnistro { get; set; }
        public virtual ICollection<grupo_reactivoxcontrato_suministro> grupo_reactivoxcontrato_suministro { get; set; }
        public virtual ICollection<log_cambios_estado_contratos_suministro> log_cambios_estado_contratos_suministro { get; set; }
        public virtual ICollection<polizas_contrato_suministro> polizas_contrato_suministro { get; set; }
        public virtual ICollection<producto_experiencia_contratoxcontrato_conmsumo> producto_experiencia_contratoxcontrato_conmsumo { get; set; }
    }
}
