//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class control_calidad
    {
        public control_calidad()
        {
            this.archivos_control_calidad = new HashSet<archivos_control_calidad>();
            this.observicionesxseguimiento_control_calidad = new HashSet<observicionesxseguimiento_control_calidad>();
        }
    
        public int cod_control_calidad { get; set; }
        public Nullable<int> cod_estado_control_calidad { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public int creado_por { get; set; }
        public string nitCliente { get; set; }
        public string codSucursal { get; set; }
        public string codContacto { get; set; }
        public Nullable<int> cod_referencia_reactivo { get; set; }
        public string lote_reactivo { get; set; }
        public Nullable<System.DateTime> fecha_vencimiento_reactivo { get; set; }
        public string cantidad_recibida { get; set; }
        public string motivo { get; set; }
        public string entregado_por { get; set; }
        public Nullable<int> recibido_por { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> asignado_a { get; set; }
        public Nullable<System.DateTime> fecha_anulacion { get; set; }
        public Nullable<bool> es_anulada { get; set; }
        public Nullable<int> anulada_por { get; set; }
        public string observaciones_anulacion { get; set; }
        public Nullable<bool> realizado_local { get; set; }
        public string numero_factura { get; set; }
        public Nullable<System.DateTime> fecha_factura { get; set; }
        public Nullable<System.DateTime> fecha_apertura_producto { get; set; }
        public Nullable<System.DateTime> fecha_inconveniente { get; set; }
        public Nullable<System.DateTime> fecha_llegada_producto { get; set; }
        public Nullable<System.DateTime> fecha_procesamiento { get; set; }
        public Nullable<System.DateTime> fecha_generacion_reporte { get; set; }
        public Nullable<System.DateTime> fecha_envio_aprobacion { get; set; }
        public Nullable<System.DateTime> fecha_aprobacion { get; set; }
        public string motivo_solicitud { get; set; }
        public string cod_revision_estado_producto { get; set; }
        public Nullable<int> cod_calibracion_calidad { get; set; }
        public string txt_controles_calidad { get; set; }
        public Nullable<bool> procesamiento_muestra_valores { get; set; }
        public string comparacion_resultados { get; set; }
        public string resultados_control_calidad { get; set; }
        public string muestras { get; set; }
        public string codFabricanteUtilizado { get; set; }
        public Nullable<bool> analisis_confidencial { get; set; }
        public string codModeloutilizado { get; set; }
        public string conclusiones { get; set; }
        public Nullable<bool> performance_adecuado { get; set; }
        public string motivo_performance { get; set; }
        public Nullable<bool> problema_identificado { get; set; }
        public string razon_problema_identificado { get; set; }
        public Nullable<bool> concepto_reposicion { get; set; }
        public string razon_concepto_reposicion { get; set; }
        public string cantidad_a_reponer { get; set; }
        public Nullable<bool> dar_baja { get; set; }
        public Nullable<System.DateTime> fecha_dar_baja { get; set; }
        public Nullable<bool> devolucion_cliente { get; set; }
        public Nullable<System.DateTime> fecha_devolucion_cliente { get; set; }
        public Nullable<bool> devolucion_proveedor { get; set; }
        public Nullable<System.DateTime> fecha_devolucion_proveedor { get; set; }
        public Nullable<int> responsable_aprobacion { get; set; }
        public Nullable<bool> aplica_reclamo_proveedor { get; set; }
        public Nullable<System.DateTime> fecha_envio_reclamo { get; set; }
        public Nullable<System.DateTime> fecha_respuesta_proveedor { get; set; }
        public string recomendaciones { get; set; }
        public Nullable<int> especialista { get; set; }
        public Nullable<bool> reposicion_aprobada { get; set; }
        public Nullable<int> reposicion_aprobada_por { get; set; }
        public string ticket_garantia { get; set; }
        public Nullable<System.DateTime> fecha_tramite_garantia { get; set; }
        public Nullable<int> reposicion_tramitada_por { get; set; }
        public Nullable<System.DateTime> fecha_reporte_asesor { get; set; }
        public Nullable<System.DateTime> fecha_reporte_cliente { get; set; }
        public Nullable<int> cod_llamada { get; set; }
        public string cliente_interno { get; set; }
        public Nullable<System.DateTime> fecha_inicio_programacion { get; set; }
        public Nullable<System.DateTime> fecha_fin_programacion { get; set; }
        public string resultados_previos_html { get; set; }
        public string resultados_html { get; set; }
        public string analisis_posibles_fallas { get; set; }
        public string antecedentes { get; set; }
        public string acciones_implementadas { get; set; }
        public string resultados_previos_txt { get; set; }
        public string resultados_txt { get; set; }
        public string analisis_posibles_fallas_txt { get; set; }
        public string conclusiones_txt { get; set; }
    
        public virtual ICollection<archivos_control_calidad> archivos_control_calidad { get; set; }
        public virtual asesoria_cientifica asesoria_cientifica { get; set; }
        public virtual contactosClientes contactosClientes { get; set; }
        public virtual estado_control_calidad estado_control_calidad { get; set; }
        public virtual Modelos Modelos { get; set; }
        public virtual referencia_reactivo referencia_reactivo { get; set; }
        public virtual sucursalCliente sucursalCliente { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
        public virtual usuario usuario2 { get; set; }
        public virtual usuario usuario3 { get; set; }
        public virtual usuario usuario4 { get; set; }
        public virtual usuario usuario5 { get; set; }
        public virtual usuario usuario6 { get; set; }
        public virtual usuario usuario7 { get; set; }
        public virtual ICollection<observicionesxseguimiento_control_calidad> observicionesxseguimiento_control_calidad { get; set; }
    }
}
