//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class departamentos
    {
        public departamentos()
        {
            this.ciudades = new HashSet<ciudades>();
        }
    
        public string codPais { get; set; }
        public string codDepartamento { get; set; }
        public string NombreDepartamento { get; set; }
    
        public virtual ICollection<ciudades> ciudades { get; set; }
        public virtual paises paises { get; set; }
    }
}
