//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class departamento
    {
        public departamento()
        {
            this.ciudad = new HashSet<ciudad>();
        }
    
        public int cod_departamento { get; set; }
        public Nullable<int> cod_pais { get; set; }
        public string nombre_departamento { get; set; }
        public string cod_manual { get; set; }
    
        public virtual ICollection<ciudad> ciudad { get; set; }
        public virtual pais pais { get; set; }
    }
}
