//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_movimiento
    {
        public detalle_movimiento()
        {
            this.informacion_extendida_detalle = new HashSet<informacion_extendida_detalle>();
            this.novedad_movimiento = new HashSet<novedad_movimiento>();
        }
    
        public long cod_detalle_movimiento { get; set; }
        public long cod_movimiento { get; set; }
        public Nullable<int> numero_item { get; set; }
        public Nullable<int> creado_por { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<int> cod_referencia { get; set; }
        public Nullable<int> cod_bodega { get; set; }
        public Nullable<int> cod_ubicacion { get; set; }
        public string serial { get; set; }
        public string serial_rango { get; set; }
        public string documento_principal { get; set; }
        public Nullable<decimal> precio { get; set; }
        public string bulto { get; set; }
        public string caja_madre { get; set; }
        public string estiba { get; set; }
        public Nullable<int> cod_estado_bloqueo { get; set; }
        public Nullable<int> cod_estado_fisico { get; set; }
        public Nullable<int> cod_estado_proceso_item { get; set; }
        public string cod_alterno { get; set; }
        public string numero_control { get; set; }
        public Nullable<System.DateTime> fecha_control { get; set; }
        public Nullable<double> cantidad { get; set; }
        public Nullable<double> cantidad_acumulada { get; set; }
        public Nullable<double> cantidad_definitiva { get; set; }
        public Nullable<System.DateTime> fecha_adicional { get; set; }
        public string texto_adicional { get; set; }
        public Nullable<int> cod_bodega_destino { get; set; }
        public Nullable<int> cod_ubicacion_destino { get; set; }
        public Nullable<double> volumen { get; set; }
        public Nullable<double> alto { get; set; }
        public Nullable<double> largo { get; set; }
        public Nullable<double> ancho { get; set; }
        public Nullable<int> cod_unidad_medida { get; set; }
        public Nullable<decimal> peso { get; set; }
        public Nullable<int> cod_unidad_peso { get; set; }
        public Nullable<int> usuario_ejecucion { get; set; }
        public Nullable<System.DateTime> fecha_ejecucion { get; set; }
        public string obs_ejecucion { get; set; }
        public Nullable<int> cod_cliente { get; set; }
        public Nullable<int> cod_foraneo1 { get; set; }
        public Nullable<int> cod_foraneo2 { get; set; }
        public Nullable<int> cod_foraneo3 { get; set; }
        public string texto1 { get; set; }
        public string texto2 { get; set; }
        public string texto3 { get; set; }
        public string txt1 { get; set; }
        public string txt2 { get; set; }
        public string txt3 { get; set; }
        public string txt4 { get; set; }
        public string txt5 { get; set; }
        public string txt6 { get; set; }
        public string txt7 { get; set; }
        public string txt8 { get; set; }
        public string txt9 { get; set; }
        public string txt10 { get; set; }
        public string txt11 { get; set; }
        public string txt12 { get; set; }
        public string txt13 { get; set; }
        public string txt14 { get; set; }
        public string txt15 { get; set; }
        public string txt16 { get; set; }
        public string txt17 { get; set; }
        public string txt18 { get; set; }
        public string txt19 { get; set; }
        public string txt20 { get; set; }
        public Nullable<double> num1 { get; set; }
        public Nullable<double> num2 { get; set; }
        public Nullable<double> num3 { get; set; }
        public Nullable<double> num4 { get; set; }
        public Nullable<double> num5 { get; set; }
        public Nullable<double> num6 { get; set; }
        public Nullable<double> num7 { get; set; }
        public Nullable<double> num8 { get; set; }
        public Nullable<double> num9 { get; set; }
        public Nullable<double> num10 { get; set; }
        public Nullable<double> num11 { get; set; }
        public Nullable<double> num12 { get; set; }
        public Nullable<double> num13 { get; set; }
        public Nullable<double> num14 { get; set; }
        public Nullable<double> num15 { get; set; }
        public Nullable<double> num16 { get; set; }
        public Nullable<double> num17 { get; set; }
        public Nullable<double> num18 { get; set; }
        public Nullable<double> num19 { get; set; }
        public Nullable<double> num20 { get; set; }
        public Nullable<System.DateTime> cal1 { get; set; }
        public Nullable<System.DateTime> cal2 { get; set; }
        public Nullable<System.DateTime> cal3 { get; set; }
        public Nullable<System.DateTime> cal4 { get; set; }
        public Nullable<System.DateTime> cal5 { get; set; }
        public Nullable<System.DateTime> cal6 { get; set; }
        public Nullable<System.DateTime> cal7 { get; set; }
        public Nullable<System.DateTime> cal8 { get; set; }
        public Nullable<System.DateTime> cal9 { get; set; }
        public Nullable<System.DateTime> cal10 { get; set; }
        public Nullable<System.DateTime> cal11 { get; set; }
        public Nullable<System.DateTime> cal12 { get; set; }
        public Nullable<System.DateTime> cal13 { get; set; }
        public Nullable<System.DateTime> cal14 { get; set; }
        public Nullable<System.DateTime> cal15 { get; set; }
        public Nullable<System.DateTime> cal16 { get; set; }
        public Nullable<System.DateTime> cal17 { get; set; }
        public Nullable<System.DateTime> cal18 { get; set; }
        public Nullable<System.DateTime> cal19 { get; set; }
        public Nullable<System.DateTime> cal20 { get; set; }
        public Nullable<int> for1 { get; set; }
        public Nullable<int> for2 { get; set; }
        public Nullable<int> for3 { get; set; }
        public Nullable<int> for4 { get; set; }
        public Nullable<int> for5 { get; set; }
        public Nullable<int> for6 { get; set; }
        public Nullable<int> for7 { get; set; }
        public Nullable<int> for8 { get; set; }
        public Nullable<int> for9 { get; set; }
        public Nullable<int> for10 { get; set; }
        public Nullable<int> for11 { get; set; }
        public Nullable<int> for12 { get; set; }
        public Nullable<int> for13 { get; set; }
        public Nullable<int> for14 { get; set; }
        public Nullable<int> for15 { get; set; }
        public Nullable<int> for16 { get; set; }
        public Nullable<int> for17 { get; set; }
        public Nullable<int> for18 { get; set; }
        public Nullable<int> for19 { get; set; }
        public Nullable<int> for20 { get; set; }
        public Nullable<bool> ind1 { get; set; }
        public Nullable<bool> ind2 { get; set; }
        public Nullable<bool> ind3 { get; set; }
        public Nullable<bool> ind4 { get; set; }
        public Nullable<bool> ind5 { get; set; }
        public Nullable<bool> ind6 { get; set; }
        public Nullable<bool> ind7 { get; set; }
        public Nullable<bool> ind8 { get; set; }
        public Nullable<bool> ind9 { get; set; }
        public Nullable<bool> ind10 { get; set; }
        public Nullable<bool> ind11 { get; set; }
        public Nullable<bool> ind12 { get; set; }
        public Nullable<bool> ind13 { get; set; }
        public Nullable<bool> ind14 { get; set; }
        public Nullable<bool> ind15 { get; set; }
        public Nullable<bool> ind16 { get; set; }
        public Nullable<bool> ind17 { get; set; }
        public Nullable<bool> ind18 { get; set; }
        public Nullable<bool> ind19 { get; set; }
        public Nullable<bool> ind20 { get; set; }
        public string txtl1 { get; set; }
        public string txtl2 { get; set; }
        public string txtl3 { get; set; }
        public string txtl4 { get; set; }
        public string txtl5 { get; set; }
        public Nullable<int> cod_ubicacion2 { get; set; }
        public Nullable<int> cod_ubicacion3 { get; set; }
        public Nullable<int> cod_ubicacion4 { get; set; }
        public Nullable<int> cod_ubicacion5 { get; set; }
        public Nullable<int> cod_ubicacion6 { get; set; }
        public Nullable<int> cod_ubicacion7 { get; set; }
        public Nullable<int> cod_ubicacion8 { get; set; }
        public Nullable<int> cod_ubicacion9 { get; set; }
        public Nullable<int> cod_ubicacion10 { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual estado_bloqueo estado_bloqueo { get; set; }
        public virtual estado_fisico estado_fisico { get; set; }
        public virtual estado_proceso_item estado_proceso_item { get; set; }
        public virtual movimiento movimiento { get; set; }
        public virtual referencia referencia { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
        public virtual ICollection<informacion_extendida_detalle> informacion_extendida_detalle { get; set; }
        public virtual ICollection<novedad_movimiento> novedad_movimiento { get; set; }
    }
}
