//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class dispositivosmedicionxordenservicio
    {
        public int cod_dispositivosmedicionxordenservicio { get; set; }
        public string serial_herramienta { get; set; }
        public Nullable<int> codOrdenServicio { get; set; }
        public string codFabricante { get; set; }
        public string codModelo { get; set; }
        public string serial_externo { get; set; }
        public string responsable_externo { get; set; }
        public string fabricante_externo { get; set; }
        public string modelo_externo { get; set; }
    
        public virtual equipos equipos { get; set; }
        public virtual Modelos Modelos { get; set; }
        public virtual ordenServicio ordenServicio { get; set; }
    }
}
