//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class estado_movimientoxusuario
    {
        public int cod_estado_movimientoxusuario { get; set; }
        public int cod_usuario { get; set; }
        public int cod_estado_movimiento { get; set; }
    
        public virtual estado_movimiento estado_movimiento { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
