//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class estadosSolicitud
    {
        public estadosSolicitud()
        {
            this.solicitudServicio = new HashSet<solicitudServicio>();
        }
    
        public int codEstadoSolicitud { get; set; }
        public string descripcionSolicitud { get; set; }
    
        public virtual ICollection<solicitudServicio> solicitudServicio { get; set; }
    }
}
