//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class estado_bloqueo
    {
        public estado_bloqueo()
        {
            this.detalle_movimiento = new HashSet<detalle_movimiento>();
            this.existencia = new HashSet<existencia>();
            this.movimiento = new HashSet<movimiento>();
        }
    
        public int cod_estado_bloqueo { get; set; }
        public Nullable<int> cod_linea { get; set; }
        public string nombre_estado_bloqueo { get; set; }
        public Nullable<bool> bloquea_inventario { get; set; }
        public Nullable<int> cod_tipo_estado_bloqueo { get; set; }
        public Nullable<bool> ind_1 { get; set; }
        public Nullable<bool> ind_2 { get; set; }
        public Nullable<bool> ind_3 { get; set; }
        public Nullable<bool> ind_4 { get; set; }
    
        public virtual ICollection<detalle_movimiento> detalle_movimiento { get; set; }
        public virtual linea linea { get; set; }
        public virtual tipo_estado_bloqueo tipo_estado_bloqueo { get; set; }
        public virtual ICollection<existencia> existencia { get; set; }
        public virtual ICollection<movimiento> movimiento { get; set; }
    }
}
