//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class estado_control_calidad
    {
        public estado_control_calidad()
        {
            this.control_calidad = new HashSet<control_calidad>();
        }
    
        public int cod_estado_control_calidad { get; set; }
        public string estado_control_calidad1 { get; set; }
        public bool activo { get; set; }
        public int cod_manual { get; set; }
    
        public virtual ICollection<control_calidad> control_calidad { get; set; }
    }
}
