//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class estadoRecoleccion
    {
        public estadoRecoleccion()
        {
            this.recoleccion = new HashSet<recoleccion>();
        }
    
        public int codEstadoRecoleccion { get; set; }
        public Nullable<int> jerarquiaEstadoRecoleccion { get; set; }
        public string nombreEstadoRecoleccion { get; set; }
    
        public virtual ICollection<recoleccion> recoleccion { get; set; }
    }
}
