//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class estadosOrdenPrestamo
    {
        public estadosOrdenPrestamo()
        {
            this.OrdenPrestamo = new HashSet<OrdenPrestamo>();
        }
    
        public int codEstadoOrdenPrestamo { get; set; }
        public string nombreEstadoOP { get; set; }
        public string descripcionEstadoOP { get; set; }
    
        public virtual ICollection<OrdenPrestamo> OrdenPrestamo { get; set; }
    }
}
