//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class estadoLocalEquipos
    {
        public estadoLocalEquipos()
        {
            this.equipos = new HashSet<equipos>();
            this.equipos1 = new HashSet<equipos>();
        }
    
        public string codEstadoLocal { get; set; }
        public string nombreEstadoLocal { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<equipos> equipos { get; set; }
        public virtual ICollection<equipos> equipos1 { get; set; }
    }
}
