//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class estado_solicitud_general
    {
        public estado_solicitud_general()
        {
            this.solicitud_general = new HashSet<solicitud_general>();
        }
    
        public int cod_estado_solicitud_general { get; set; }
        public Nullable<int> cod_manual { get; set; }
        public string nombre_estado_solicitud { get; set; }
    
        public virtual ICollection<solicitud_general> solicitud_general { get; set; }
    }
}
