//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fabricante
    {
        public string codFabricante { get; set; }
        public string nombre_fabricante { get; set; }
        public string numero_nit { get; set; }
        public string pagina_web { get; set; }
        public string email_contacto { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
        public string nombre_contacto { get; set; }
        public string tituloContacto { get; set; }
        public byte[] logo { get; set; }
        public Nullable<int> cod_linea { get; set; }
        public int cod_fabricante { get; set; }
    
        public virtual linea linea { get; set; }
    }
}
