//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class flujoxproceso
    {
        public int cod_flujoxproceso { get; set; }
        public int cod_flujo { get; set; }
        public int cod_proceso { get; set; }
    
        public virtual flujo flujo { get; set; }
        public virtual proceso proceso { get; set; }
    }
}
