//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupo_reactivoxcontrato_suministro
    {
        public int cod_grupo_reactivoxcontrato_suministro { get; set; }
        public Nullable<int> cod_grupo_reactivo_experiencia { get; set; }
        public Nullable<int> cod_contratos_suministro { get; set; }
    
        public virtual contratos_suministro contratos_suministro { get; set; }
        public virtual grupo_reactivo_experiencia grupo_reactivo_experiencia { get; set; }
    }
}
