//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class gruposModulosxGruposUsuarios
    {
        public string codGrupoModulo { get; set; }
        public string codGruposUsu { get; set; }
        public Nullable<bool> controlTotal { get; set; }
        public Nullable<bool> modificar { get; set; }
        public Nullable<bool> lecturaEjecucion { get; set; }
        public Nullable<bool> escribir { get; set; }
        public Nullable<bool> eliminar { get; set; }
        public Nullable<bool> imprimir { get; set; }
        public Nullable<bool> denegar { get; set; }
    
        public virtual gruposModulos gruposModulos { get; set; }
        public virtual gruposUsuarios gruposUsuarios { get; set; }
    }
}
