//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupo_reactivo_experiencia
    {
        public grupo_reactivo_experiencia()
        {
            this.grupo_reactivoxcontrato_suministro = new HashSet<grupo_reactivoxcontrato_suministro>();
        }
    
        public int cod_grupo_reactivo_experiencia { get; set; }
        public string nombre_grupo_reactivo_experiencia { get; set; }
    
        public virtual ICollection<grupo_reactivoxcontrato_suministro> grupo_reactivoxcontrato_suministro { get; set; }
    }
}
