//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupo_inventario
    {
        public grupo_inventario()
        {
            this.referencia = new HashSet<referencia>();
            this.ubicacionxgrupo_inventario = new HashSet<ubicacionxgrupo_inventario>();
        }
    
        public int cod_grupo_inventario { get; set; }
        public string nombre_grupo { get; set; }
        public string cod_manual { get; set; }
        public int cod_linea { get; set; }
    
        public virtual ICollection<referencia> referencia { get; set; }
        public virtual ICollection<ubicacionxgrupo_inventario> ubicacionxgrupo_inventario { get; set; }
    }
}
