//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupo_consumible
    {
        public int cod_fabricante { get; set; }
        public string grupo_consumible1 { get; set; }
        public int cod_grupo_consumible { get; set; }
    }
}
