//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupo_usuarioxlinea
    {
        public int cod_grupo_usuarioxlinea { get; set; }
        public int cod_grupo_usuario { get; set; }
        public int cod_linea { get; set; }
    
        public virtual grupo_usuario grupo_usuario { get; set; }
        public virtual linea linea { get; set; }
    }
}
