//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupo_usuario
    {
        public grupo_usuario()
        {
            this.cgq_queryxgrupo_usuario = new HashSet<cgq_queryxgrupo_usuario>();
            this.estado_movimientoxgrupo_usuario = new HashSet<estado_movimientoxgrupo_usuario>();
            this.funcionalidad_grupousuario = new HashSet<funcionalidad_grupousuario>();
            this.grupo_usuarioxlinea = new HashSet<grupo_usuarioxlinea>();
            this.grupousuario_usuario = new HashSet<grupousuario_usuario>();
            this.moduloseguridad_grupousuario = new HashSet<moduloseguridad_grupousuario>();
            this.notificacion_estado_copia_grupo = new HashSet<notificacion_estado_copia_grupo>();
        }
    
        public int cod_grupo_usuario { get; set; }
        public string nombre_grupo_usuario { get; set; }
    
        public virtual ICollection<cgq_queryxgrupo_usuario> cgq_queryxgrupo_usuario { get; set; }
        public virtual ICollection<estado_movimientoxgrupo_usuario> estado_movimientoxgrupo_usuario { get; set; }
        public virtual ICollection<funcionalidad_grupousuario> funcionalidad_grupousuario { get; set; }
        public virtual ICollection<grupo_usuarioxlinea> grupo_usuarioxlinea { get; set; }
        public virtual ICollection<grupousuario_usuario> grupousuario_usuario { get; set; }
        public virtual ICollection<moduloseguridad_grupousuario> moduloseguridad_grupousuario { get; set; }
        public virtual ICollection<notificacion_estado_copia_grupo> notificacion_estado_copia_grupo { get; set; }
    }
}
