//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class gruposUsuarios
    {
        public gruposUsuarios()
        {
            this.gruposModulosxGruposUsuarios = new HashSet<gruposModulosxGruposUsuarios>();
            this.gruposUsuariosxUsuario = new HashSet<gruposUsuariosxUsuario>();
            this.gruposUsuarios1 = new HashSet<gruposUsuarios>();
            this.gruposUsuarios2 = new HashSet<gruposUsuarios>();
        }
    
        public string codGruposUsu { get; set; }
        public string nombreGru { get; set; }
        public string descripcionGru { get; set; }
    
        public virtual ICollection<gruposModulosxGruposUsuarios> gruposModulosxGruposUsuarios { get; set; }
        public virtual ICollection<gruposUsuariosxUsuario> gruposUsuariosxUsuario { get; set; }
        public virtual ICollection<gruposUsuarios> gruposUsuarios1 { get; set; }
        public virtual ICollection<gruposUsuarios> gruposUsuarios2 { get; set; }
    }
}
