//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class inconveniente_presentado_cientifica
    {
        public int cod_inconveniente_presentado_cientifica { get; set; }
        public string nombre_inconveniente { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<bool> ind_equipo { get; set; }
        public Nullable<bool> ind_reactivo { get; set; }
    }
}
