//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class incumplimientoConsumo
    {
        public incumplimientoConsumo()
        {
            this.archivosxIncumplimiento = new HashSet<archivosxIncumplimiento>();
        }
    
        public string numeroContrato { get; set; }
        public int codIncumplimiento { get; set; }
        public string descripcion { get; set; }
        public string Observaciones { get; set; }
        public string creadoPor { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
    
        public virtual ICollection<archivosxIncumplimiento> archivosxIncumplimiento { get; set; }
    }
}
