//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class indicacionesLLamadas
    {
        public int idLLamadaSoporte { get; set; }
        public int codIndicacion { get; set; }
        public string ingresadaPor { get; set; }
        public string descripcion { get; set; }
        public string observaciones { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaIndicacion { get; set; }
    
        public virtual LlamadaSoporte LlamadaSoporte { get; set; }
    }
}
