//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class informacion_extendida_detalle
    {
        public int cod_informacion_extendida_detalle { get; set; }
        public long cod_detalle_movimiento { get; set; }
        public string texto1 { get; set; }
        public string texto2 { get; set; }
        public string texto3 { get; set; }
        public string texto4 { get; set; }
        public string texto5 { get; set; }
        public string texto6 { get; set; }
        public Nullable<System.DateTime> fecha1 { get; set; }
        public Nullable<System.DateTime> fecha2 { get; set; }
        public Nullable<System.DateTime> fecha3 { get; set; }
        public Nullable<System.DateTime> fecha4 { get; set; }
        public Nullable<System.DateTime> fecha5 { get; set; }
        public Nullable<System.DateTime> fecha6 { get; set; }
        public Nullable<System.DateTime> fecha7 { get; set; }
        public Nullable<System.DateTime> fecha8 { get; set; }
        public Nullable<System.DateTime> fecha9 { get; set; }
        public Nullable<System.DateTime> fecha10 { get; set; }
        public Nullable<System.DateTime> fecha11 { get; set; }
        public Nullable<System.DateTime> fecha12 { get; set; }
        public Nullable<System.DateTime> fecha13 { get; set; }
        public Nullable<System.DateTime> fecha14 { get; set; }
        public Nullable<System.DateTime> fecha15 { get; set; }
        public Nullable<System.DateTime> fecha16 { get; set; }
        public Nullable<System.DateTime> fecha17 { get; set; }
        public Nullable<System.DateTime> fecha18 { get; set; }
        public Nullable<System.DateTime> fecha19 { get; set; }
        public Nullable<System.DateTime> fecha20 { get; set; }
        public Nullable<double> numero1 { get; set; }
        public Nullable<double> numero2 { get; set; }
        public Nullable<double> numero3 { get; set; }
        public Nullable<double> numero4 { get; set; }
        public Nullable<double> numero5 { get; set; }
        public Nullable<double> numero6 { get; set; }
    
        public virtual detalle_movimiento detalle_movimiento { get; set; }
    }
}
