//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class informacion_adicional_usuario
    {
        public int cod_informacion_adicional_usuario { get; set; }
        public int cod_usuario { get; set; }
        public string cargo { get; set; }
        public string profesion { get; set; }
        public byte[] imagen_firma { get; set; }
    }
}
