//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class layout_flujo
    {
        public layout_flujo()
        {
            this.layout_linea_flujo = new HashSet<layout_linea_flujo>();
            this.layout_linea_flujo1 = new HashSet<layout_linea_flujo>();
        }
    
        public int cod_layout_flujo { get; set; }
        public Nullable<int> cod_flujo { get; set; }
        public Nullable<int> cod_proceso { get; set; }
        public Nullable<int> cod_estado { get; set; }
        public int x { get; set; }
        public int y { get; set; }
        public int w { get; set; }
        public int h { get; set; }
        public int borde_r { get; set; }
        public int borde_g { get; set; }
        public int borde_b { get; set; }
        public int border_size { get; set; }
        public Nullable<int> fill_r { get; set; }
        public Nullable<int> fill_g { get; set; }
        public Nullable<int> fill_b { get; set; }
        public Nullable<int> fill2_r { get; set; }
        public Nullable<int> fill2_g { get; set; }
        public Nullable<int> fill2_b { get; set; }
        public Nullable<int> opaco { get; set; }
        public bool es_nota { get; set; }
        public string texto_nota { get; set; }
    
        public virtual estado_movimiento estado_movimiento { get; set; }
        public virtual flujo flujo { get; set; }
        public virtual proceso proceso { get; set; }
        public virtual ICollection<layout_linea_flujo> layout_linea_flujo { get; set; }
        public virtual ICollection<layout_linea_flujo> layout_linea_flujo1 { get; set; }
    }
}
