//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class lineasConsumo
    {
        public lineasConsumo()
        {
            this.consumoContratoxLinea = new HashSet<consumoContratoxLinea>();
        }
    
        public string codGrupoLineaConsumo { get; set; }
        public string codLinea { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<consumoContratoxLinea> consumoContratoxLinea { get; set; }
        public virtual gruposLineasConsumo gruposLineasConsumo { get; set; }
    }
}
