//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LlamadaSoporte
    {
        public LlamadaSoporte()
        {
            this.asesoria_cientifica = new HashSet<asesoria_cientifica>();
            this.indicacionesLLamadas = new HashSet<indicacionesLLamadas>();
            this.LlamadaSoportePre = new HashSet<LlamadaSoportePre>();
            this.problemas_frecuentes_por_llamada = new HashSet<problemas_frecuentes_por_llamada>();
            this.seguimiento = new HashSet<seguimiento>();
        }
    
        public int idLlamadaSoporte { get; set; }
        public string codEstadoLLamadaTecnica { get; set; }
        public Nullable<System.DateTime> fechaLlamada { get; set; }
        public Nullable<bool> llamadaRecibida { get; set; }
        public string nitCliente { get; set; }
        public string codUbicacion { get; set; }
        public string codContacto { get; set; }
        public string infAdicionalContacto { get; set; }
        public string serial { get; set; }
        public string codModalidadEquipo { get; set; }
        public string asesorTelefonico { get; set; }
        public string ingenieroAsesor { get; set; }
        public Nullable<System.DateTime> fechaAsignacionIngeniero { get; set; }
        public Nullable<int> codAsesor { get; set; }
        public string obsCliente { get; set; }
        public string obsAsesorTelefonico { get; set; }
        public Nullable<bool> solucionado { get; set; }
        public string obsFinales { get; set; }
        public Nullable<System.DateTime> fechaCierre { get; set; }
        public string cerradaPor { get; set; }
        public Nullable<int> codSolicitud { get; set; }
        public string nombreUsuarioCliente { get; set; }
        public Nullable<System.DateTime> fechaSolucion { get; set; }
        public Nullable<int> diasEnSolucionar { get; set; }
        public Nullable<System.DateTime> fechaUltimoSeguimiento { get; set; }
        public Nullable<int> cod_tipo_asesoria { get; set; }
        public Nullable<int> cod_resultado_final_llamada { get; set; }
        public Nullable<int> versionReporte { get; set; }
    
        public virtual asesoresComerciales asesoresComerciales { get; set; }
        public virtual ICollection<asesoria_cientifica> asesoria_cientifica { get; set; }
        public virtual contactosClientes contactosClientes { get; set; }
        public virtual equipos equipos { get; set; }
        public virtual estadosLLamadasTecnicas estadosLLamadasTecnicas { get; set; }
        public virtual ICollection<indicacionesLLamadas> indicacionesLLamadas { get; set; }
        public virtual ModalidadEquipo ModalidadEquipo { get; set; }
        public virtual solicitudServicio solicitudServicio { get; set; }
        public virtual sucursalCliente sucursalCliente { get; set; }
        public virtual ICollection<LlamadaSoportePre> LlamadaSoportePre { get; set; }
        public virtual ICollection<problemas_frecuentes_por_llamada> problemas_frecuentes_por_llamada { get; set; }
        public virtual ICollection<seguimiento> seguimiento { get; set; }
    }
}
