//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LlamadaSoportePre
    {
        public LlamadaSoportePre()
        {
            this.asesoria_cientifica = new HashSet<asesoria_cientifica>();
        }
    
        public int idLlamadaSoportePre { get; set; }
        public string EstadoLLamadaTecnica { get; set; }
        public Nullable<System.DateTime> fechaLlamada { get; set; }
        public Nullable<bool> llamadaRecibida { get; set; }
        public string nitCliente { get; set; }
        public string codUbicacion { get; set; }
        public string codContacto { get; set; }
        public string infAdicionalContacto { get; set; }
        public string serial { get; set; }
        public string codModalidadEquipo { get; set; }
        public string asesorTelefonico { get; set; }
        public string ingenieroAsesor { get; set; }
        public Nullable<System.DateTime> fechaAsignacionIngeniero { get; set; }
        public Nullable<int> codAsesor { get; set; }
        public string obsCliente { get; set; }
        public string obsAsesorTelefonico { get; set; }
        public Nullable<bool> solucionado { get; set; }
        public string obsFinales { get; set; }
        public Nullable<System.DateTime> fechaCierre { get; set; }
        public string cerradaPor { get; set; }
        public Nullable<int> codSolicitud { get; set; }
        public Nullable<System.DateTime> fechaSolucion { get; set; }
        public Nullable<int> diasEnSolucionar { get; set; }
        public Nullable<System.DateTime> fechaUltimoSeguimiento { get; set; }
        public Nullable<int> idLlamadaSoporte { get; set; }
    
        public virtual ICollection<asesoria_cientifica> asesoria_cientifica { get; set; }
        public virtual LlamadaSoporte LlamadaSoporte { get; set; }
    }
}
