//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_cambio_contratos_consumo
    {
        public int cod_log_cambio_contratos_consumo { get; set; }
        public string numero_contrato { get; set; }
        public Nullable<int> equipos_agregados { get; set; }
        public Nullable<int> equipos_eliminados { get; set; }
        public Nullable<int> equipos_totales { get; set; }
        public Nullable<int> software_agregado { get; set; }
        public Nullable<int> software_eliminado { get; set; }
        public Nullable<int> software_total { get; set; }
        public decimal consumo_total { get; set; }
        public Nullable<System.DateTime> fecha_cambio { get; set; }
        public Nullable<int> cod_contrato_consumo { get; set; }
        public string otro_si { get; set; }
    }
}
