//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModalidadEquipo
    {
        public ModalidadEquipo()
        {
            this.equipos = new HashSet<equipos>();
            this.equipos1 = new HashSet<equipos>();
            this.LlamadaSoporte = new HashSet<LlamadaSoporte>();
            this.logCambioUbicaciones = new HashSet<logCambioUbicaciones>();
            this.logCambioUbicaciones1 = new HashSet<logCambioUbicaciones>();
            this.ordenServicio = new HashSet<ordenServicio>();
            this.recoleccion = new HashSet<recoleccion>();
            this.solicitudServicio = new HashSet<solicitudServicio>();
        }
    
        public string codModalidadEquipo { get; set; }
        public string nombreModalidadEquipo { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<equipos> equipos { get; set; }
        public virtual ICollection<equipos> equipos1 { get; set; }
        public virtual ICollection<LlamadaSoporte> LlamadaSoporte { get; set; }
        public virtual ICollection<logCambioUbicaciones> logCambioUbicaciones { get; set; }
        public virtual ICollection<logCambioUbicaciones> logCambioUbicaciones1 { get; set; }
        public virtual ICollection<ordenServicio> ordenServicio { get; set; }
        public virtual ICollection<recoleccion> recoleccion { get; set; }
        public virtual ICollection<solicitudServicio> solicitudServicio { get; set; }
    }
}
