//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class modalidad
    {
        public modalidad()
        {
            this.movimiento = new HashSet<movimiento>();
        }
    
        public int cod_modalidad { get; set; }
        public string nombre_modalidad { get; set; }
        public Nullable<bool> ind_1 { get; set; }
        public Nullable<bool> ind_2 { get; set; }
        public Nullable<int> cod_linea { get; set; }
    
        public virtual linea linea { get; set; }
        public virtual ICollection<movimiento> movimiento { get; set; }
    }
}
