//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class modalidad_contrato
    {
        public modalidad_contrato()
        {
            this.sub_modalidad_contrato = new HashSet<sub_modalidad_contrato>();
        }
    
        public int cod_modalidad_contrato { get; set; }
        public string nombre_modalidad_contrato { get; set; }
        public bool activo { get; set; }
    
        public virtual ICollection<sub_modalidad_contrato> sub_modalidad_contrato { get; set; }
    }
}
