//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class modalidadContrato
    {
        public modalidadContrato()
        {
            this.contratos = new HashSet<contratos>();
        }
    
        public string codModalidadContrato { get; set; }
        public string codTipoContrato { get; set; }
        public string nombreModalidadContrato { get; set; }
        public string desccripcion { get; set; }
    
        public virtual ICollection<contratos> contratos { get; set; }
        public virtual tipoContrato tipoContrato { get; set; }
    }
}
