//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class motivo_anulacion_proceso
    {
        public motivo_anulacion_proceso()
        {
            this.motivo_anulacion_movimiento = new HashSet<motivo_anulacion_movimiento>();
        }
    
        public int cod_motivo_anulacion_proceso { get; set; }
        public int cod_proceso { get; set; }
        public string descripcion_motivo_anulacion { get; set; }
    
        public virtual ICollection<motivo_anulacion_movimiento> motivo_anulacion_movimiento { get; set; }
        public virtual proceso proceso { get; set; }
    }
}
