//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class motivo_anulacion_movimiento
    {
        public int cod_motivo_anulacion_movimiento { get; set; }
        public int cod_motivo_anulacion_proceso { get; set; }
        public long cod_movimiento { get; set; }
        public string observaciones_adicionales { get; set; }
        public System.DateTime fecha_anulacion { get; set; }
    
        public virtual motivo_anulacion_proceso motivo_anulacion_proceso { get; set; }
        public virtual movimiento movimiento { get; set; }
    }
}
