//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class motivo_anulacion_cientifica
    {
        public int cod_motivo_anulacion_cientifica { get; set; }
        public string motivo_anulacion { get; set; }
    }
}
