//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class movimiento
    {
        public movimiento()
        {
            this.archivo_movimiento = new HashSet<archivo_movimiento>();
            this.detalle_movimiento = new HashSet<detalle_movimiento>();
            this.existencia = new HashSet<existencia>();
            this.existencia1 = new HashSet<existencia>();
            this.informacion_extendida_movimiento = new HashSet<informacion_extendida_movimiento>();
            this.logcambia_estado = new HashSet<logcambia_estado>();
            this.motivo_anulacion_movimiento = new HashSet<motivo_anulacion_movimiento>();
            this.novedad_movimiento = new HashSet<novedad_movimiento>();
            this.novedad_movimiento1 = new HashSet<novedad_movimiento>();
        }
    
        public long cod_movimiento { get; set; }
        public int cod_linea { get; set; }
        public int cod_estado_movimiento { get; set; }
        public Nullable<int> cod_tipo_movimiento { get; set; }
        public Nullable<int> cod_prioridad_movimiento { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public int usuario_creacion { get; set; }
        public Nullable<long> consecutivo_linea { get; set; }
        public Nullable<long> consecutivo_proceso { get; set; }
        public Nullable<long> consecutivo_linea_proceso { get; set; }
        public int cod_proceso_semilla { get; set; }
        public int cod_estado_semilla { get; set; }
        public Nullable<long> cod_movimiento_semilla { get; set; }
        public Nullable<long> cod_movimiento_agrupador { get; set; }
        public Nullable<long> cod_movimiento_padre { get; set; }
        public Nullable<long> cod_movimiento_padre_alterno { get; set; }
        public Nullable<bool> espera_flujo_alterno { get; set; }
        public string observaciones_iniciales { get; set; }
        public string ultimas_observaciones { get; set; }
        public bool movimiento_historico { get; set; }
        public Nullable<int> periodo_ano { get; set; }
        public Nullable<int> periodo_mes { get; set; }
        public Nullable<int> periodo_dia { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public Nullable<System.DateTime> fecha_ultimo_cambio { get; set; }
        public Nullable<System.DateTime> fecha_tentativa_ejecucion { get; set; }
        public Nullable<System.DateTime> fecha_fin_tentativa_ejecucion { get; set; }
        public Nullable<System.DateTime> fecha_ejecucion { get; set; }
        public Nullable<System.DateTime> fecha_fin_ejecucion { get; set; }
        public Nullable<int> usuario_fin { get; set; }
        public Nullable<int> usuario_ejecucion { get; set; }
        public Nullable<int> usuario_ultimo_cambio { get; set; }
        public Nullable<int> usuario_responsable { get; set; }
        public Nullable<int> usuario_anulacion { get; set; }
        public string documento_principal { get; set; }
        public string documento_adicional { get; set; }
        public string documento_transporte { get; set; }
        public string factura { get; set; }
        public Nullable<int> color_r { get; set; }
        public Nullable<int> color_g { get; set; }
        public Nullable<int> color_b { get; set; }
        public string texto_alarma { get; set; }
        public Nullable<double> total_unidades { get; set; }
        public Nullable<double> total_bultos { get; set; }
        public Nullable<double> total_volumen { get; set; }
        public Nullable<int> total_novedades { get; set; }
        public Nullable<int> total_archivos { get; set; }
        public Nullable<double> total_peso { get; set; }
        public Nullable<double> valor_unidades { get; set; }
        public Nullable<int> unidades_pendientes_ejecucion { get; set; }
        public Nullable<int> cod_foraneo1 { get; set; }
        public Nullable<int> cod_foraneo2 { get; set; }
        public Nullable<int> cod_cliente { get; set; }
        public Nullable<int> cod_sucursal_cliente { get; set; }
        public Nullable<int> cod_proveedor { get; set; }
        public Nullable<int> cod_transportador { get; set; }
        public Nullable<int> cod_ciudad { get; set; }
        public Nullable<int> cod_tipo_servicio { get; set; }
        public Nullable<int> cod_estado_fisico { get; set; }
        public Nullable<int> cod_estado_bloqueo { get; set; }
        public Nullable<int> cod_bodega { get; set; }
        public Nullable<int> cod_ubicacion { get; set; }
        public Nullable<int> cod_modalidad { get; set; }
        public Nullable<long> cod_movimiento_maestro { get; set; }
        public string txt1 { get; set; }
        public string txt2 { get; set; }
        public string txt3 { get; set; }
        public string txt4 { get; set; }
        public string txt5 { get; set; }
        public string txt6 { get; set; }
        public string txt7 { get; set; }
        public string txt8 { get; set; }
        public string txt9 { get; set; }
        public string txt10 { get; set; }
        public string txt11 { get; set; }
        public string txt12 { get; set; }
        public string txt13 { get; set; }
        public string txt14 { get; set; }
        public string txt15 { get; set; }
        public string txt16 { get; set; }
        public string txt17 { get; set; }
        public string txt18 { get; set; }
        public string txt19 { get; set; }
        public string txt20 { get; set; }
        public Nullable<double> num1 { get; set; }
        public Nullable<double> num2 { get; set; }
        public Nullable<double> num3 { get; set; }
        public Nullable<double> num4 { get; set; }
        public Nullable<double> num5 { get; set; }
        public Nullable<double> num6 { get; set; }
        public Nullable<double> num7 { get; set; }
        public Nullable<double> num8 { get; set; }
        public Nullable<double> num9 { get; set; }
        public Nullable<double> num10 { get; set; }
        public Nullable<double> num11 { get; set; }
        public Nullable<double> num12 { get; set; }
        public Nullable<double> num13 { get; set; }
        public Nullable<double> num14 { get; set; }
        public Nullable<double> num15 { get; set; }
        public Nullable<double> num16 { get; set; }
        public Nullable<double> num17 { get; set; }
        public Nullable<double> num18 { get; set; }
        public Nullable<double> num19 { get; set; }
        public Nullable<double> num20 { get; set; }
        public Nullable<System.DateTime> cal1 { get; set; }
        public Nullable<System.DateTime> cal2 { get; set; }
        public Nullable<System.DateTime> cal3 { get; set; }
        public Nullable<System.DateTime> cal4 { get; set; }
        public Nullable<System.DateTime> cal5 { get; set; }
        public Nullable<System.DateTime> cal6 { get; set; }
        public Nullable<System.DateTime> cal7 { get; set; }
        public Nullable<System.DateTime> cal8 { get; set; }
        public Nullable<System.DateTime> cal9 { get; set; }
        public Nullable<System.DateTime> cal10 { get; set; }
        public Nullable<System.DateTime> cal11 { get; set; }
        public Nullable<System.DateTime> cal12 { get; set; }
        public Nullable<System.DateTime> cal13 { get; set; }
        public Nullable<System.DateTime> cal14 { get; set; }
        public Nullable<System.DateTime> cal15 { get; set; }
        public Nullable<System.DateTime> cal16 { get; set; }
        public Nullable<System.DateTime> cal17 { get; set; }
        public Nullable<System.DateTime> cal18 { get; set; }
        public Nullable<System.DateTime> cal19 { get; set; }
        public Nullable<System.DateTime> cal20 { get; set; }
        public Nullable<int> for1 { get; set; }
        public Nullable<int> for2 { get; set; }
        public Nullable<int> for3 { get; set; }
        public Nullable<int> for4 { get; set; }
        public Nullable<int> for5 { get; set; }
        public Nullable<int> for6 { get; set; }
        public Nullable<int> for7 { get; set; }
        public Nullable<int> for8 { get; set; }
        public Nullable<int> for9 { get; set; }
        public Nullable<int> for10 { get; set; }
        public Nullable<int> for11 { get; set; }
        public Nullable<int> for12 { get; set; }
        public Nullable<int> for13 { get; set; }
        public Nullable<int> for14 { get; set; }
        public Nullable<int> for15 { get; set; }
        public Nullable<int> for16 { get; set; }
        public Nullable<int> for17 { get; set; }
        public Nullable<int> for18 { get; set; }
        public Nullable<int> for19 { get; set; }
        public Nullable<int> for20 { get; set; }
        public Nullable<bool> ind1 { get; set; }
        public Nullable<bool> ind2 { get; set; }
        public Nullable<bool> ind3 { get; set; }
        public Nullable<bool> ind4 { get; set; }
        public Nullable<bool> ind5 { get; set; }
        public Nullable<bool> ind6 { get; set; }
        public Nullable<bool> ind7 { get; set; }
        public Nullable<bool> ind8 { get; set; }
        public Nullable<bool> ind9 { get; set; }
        public Nullable<bool> ind10 { get; set; }
        public Nullable<bool> ind11 { get; set; }
        public Nullable<bool> ind12 { get; set; }
        public Nullable<bool> ind13 { get; set; }
        public Nullable<bool> ind14 { get; set; }
        public Nullable<bool> ind15 { get; set; }
        public Nullable<bool> ind16 { get; set; }
        public Nullable<bool> ind17 { get; set; }
        public Nullable<bool> ind18 { get; set; }
        public Nullable<bool> ind19 { get; set; }
        public Nullable<bool> ind20 { get; set; }
        public string txtl1 { get; set; }
        public string txtl2 { get; set; }
        public string txtl3 { get; set; }
        public string txtl4 { get; set; }
        public string txtl5 { get; set; }
    
        public virtual ICollection<archivo_movimiento> archivo_movimiento { get; set; }
        public virtual ciudad ciudad { get; set; }
        public virtual ICollection<detalle_movimiento> detalle_movimiento { get; set; }
        public virtual estado_bloqueo estado_bloqueo { get; set; }
        public virtual estado_fisico estado_fisico { get; set; }
        public virtual estado_movimiento estado_movimiento { get; set; }
        public virtual ICollection<existencia> existencia { get; set; }
        public virtual ICollection<existencia> existencia1 { get; set; }
        public virtual ICollection<informacion_extendida_movimiento> informacion_extendida_movimiento { get; set; }
        public virtual linea linea { get; set; }
        public virtual ICollection<logcambia_estado> logcambia_estado { get; set; }
        public virtual modalidad modalidad { get; set; }
        public virtual ICollection<motivo_anulacion_movimiento> motivo_anulacion_movimiento { get; set; }
        public virtual prioridad_movimiento prioridad_movimiento { get; set; }
        public virtual proveedor proveedor { get; set; }
        public virtual tipo_movimiento tipo_movimiento { get; set; }
        public virtual tipo_servicio tipo_servicio { get; set; }
        public virtual transportador transportador { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
        public virtual usuario usuario2 { get; set; }
        public virtual usuario usuario3 { get; set; }
        public virtual usuario usuario4 { get; set; }
        public virtual usuario usuario5 { get; set; }
        public virtual ICollection<novedad_movimiento> novedad_movimiento { get; set; }
        public virtual ICollection<novedad_movimiento> novedad_movimiento1 { get; set; }
    }
}
