//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class muelle
    {
        public int cod_muelle { get; set; }
        public Nullable<int> cod_bodega { get; set; }
        public string tipo_muelle { get; set; }
        public Nullable<int> nombre_muelle { get; set; }
    
        public virtual bodega bodega { get; set; }
    }
}
