//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class notificacion_estado_copia_usuario
    {
        public int cod_notificacion_estado_copia_usuario { get; set; }
        public int cod_notificacion_estado { get; set; }
        public int cod_usuario { get; set; }
        public bool cc { get; set; }
        public bool cco { get; set; }
    
        public virtual notificacion_estado notificacion_estado { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
