//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class notificacion_estado
    {
        public notificacion_estado()
        {
            this.notificacion_estado_copia_grupo = new HashSet<notificacion_estado_copia_grupo>();
            this.notificacion_estado_copia_usuario = new HashSet<notificacion_estado_copia_usuario>();
        }
    
        public int cod_notificacion_estado { get; set; }
        public int cod_estado_movimiento { get; set; }
        public bool activo { get; set; }
        public string asunto { get; set; }
        public string cuerpo_email { get; set; }
        public bool notificar_responsable { get; set; }
        public bool notificar_todos { get; set; }
    
        public virtual estado_movimiento estado_movimiento { get; set; }
        public virtual ICollection<notificacion_estado_copia_grupo> notificacion_estado_copia_grupo { get; set; }
        public virtual ICollection<notificacion_estado_copia_usuario> notificacion_estado_copia_usuario { get; set; }
    }
}
