//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class novedad_movimiento
    {
        public int cod_novedad_movimiento { get; set; }
        public int cod_tipo_novedad { get; set; }
        public long cod_movimiento { get; set; }
        public Nullable<long> cod_detalle_movimiento { get; set; }
        public int cod_usuario { get; set; }
        public System.DateTime fecha { get; set; }
        public string observacion { get; set; }
        public Nullable<int> cod_accion_tomada { get; set; }
        public Nullable<System.DateTime> fecha_cierre { get; set; }
        public string observacion_cierre { get; set; }
        public Nullable<int> cerrada_por { get; set; }
    
        public virtual accion_novedad accion_novedad { get; set; }
        public virtual detalle_movimiento detalle_movimiento { get; set; }
        public virtual movimiento movimiento { get; set; }
        public virtual movimiento movimiento1 { get; set; }
        public virtual tipo_novedad tipo_novedad { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
