//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class opciones_extra_proceso
    {
        public int cod_opciones_extra_proceso { get; set; }
        public int cod_proceso { get; set; }
        public string nombre_funcion { get; set; }
        public string formulario_ejecucion { get; set; }
    
        public virtual proceso proceso { get; set; }
    }
}
