//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class parametro
    {
        public int cod_parametro { get; set; }
        public Nullable<int> cod_linea { get; set; }
        public string cod_manual { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> valor_numero { get; set; }
        public string valor_texto { get; set; }
        public string texto_laargo { get; set; }
    
        public virtual linea linea { get; set; }
    }
}
