//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class pendiente_tarea
    {
        public int cod_pendiente_tarea { get; set; }
        public int cod_tarea_calendario { get; set; }
        public string pendiente { get; set; }
        public Nullable<System.DateTime> fecha_ejecucion_pendiente { get; set; }
        public Nullable<int> usuario_ejecucion { get; set; }
    
        public virtual tarea_calendario tarea_calendario { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
