//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class polizas_contrato_suministro
    {
        public int cod_polizas_contrato_suministro { get; set; }
        public Nullable<int> cod_contratos_suministro { get; set; }
        public string nombre_poliza { get; set; }
        public Nullable<int> porcentaje { get; set; }
        public Nullable<decimal> valor_poliza { get; set; }
        public Nullable<int> vigencia_meses { get; set; }
    
        public virtual contratos_suministro contratos_suministro { get; set; }
    }
}
