//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class problemas_frecuentes_por_llamada
    {
        public int cod_problemas_frecuentes_por_llamada { get; set; }
        public int cod_problema_frecuente { get; set; }
        public int idLlamadaSoporte { get; set; }
        public Nullable<int> cod_soluciones_problemas { get; set; }
    
        public virtual LlamadaSoporte LlamadaSoporte { get; set; }
        public virtual problemas_frecuentes problemas_frecuentes { get; set; }
        public virtual soluciones_problemas soluciones_problemas { get; set; }
    }
}
