//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class proceso
    {
        public proceso()
        {
            this.estado_movimiento = new HashSet<estado_movimiento>();
            this.estado_proceso_item = new HashSet<estado_proceso_item>();
            this.flujoxproceso = new HashSet<flujoxproceso>();
            this.layout_flujo = new HashSet<layout_flujo>();
            this.layout_linea_flujo = new HashSet<layout_linea_flujo>();
            this.logcambia_estado = new HashSet<logcambia_estado>();
            this.logcambia_estado1 = new HashSet<logcambia_estado>();
            this.motivo_anulacion_proceso = new HashSet<motivo_anulacion_proceso>();
            this.opciones = new HashSet<opciones>();
            this.opciones1 = new HashSet<opciones>();
            this.opciones_extra_proceso = new HashSet<opciones_extra_proceso>();
            this.prioridad_movimiento = new HashSet<prioridad_movimiento>();
            this.responsable_proceso = new HashSet<responsable_proceso>();
            this.secuencia_proceso = new HashSet<secuencia_proceso>();
            this.secuencia_proceso1 = new HashSet<secuencia_proceso>();
            this.tipo_movimiento = new HashSet<tipo_movimiento>();
            this.tipo_novedad = new HashSet<tipo_novedad>();
            this.tipo_servicio = new HashSet<tipo_servicio>();
            this.wcg_mapping = new HashSet<wcg_mapping>();
        }
    
        public int cod_proceso { get; set; }
        public string nombre_proceso { get; set; }
        public int cod_linea { get; set; }
        public string formulario_creacion { get; set; }
        public string formulario_post_creacion { get; set; }
        public string formulario_edicion { get; set; }
        public string formulario_post_edicion { get; set; }
        public Nullable<bool> es_inicio { get; set; }
        public Nullable<bool> es_fin { get; set; }
        public Nullable<int> color_r { get; set; }
        public Nullable<int> color_g { get; set; }
        public Nullable<int> color_b { get; set; }
        public Nullable<int> cod_flujo { get; set; }
        public Nullable<bool> es_maestro { get; set; }
    
        public virtual ICollection<estado_movimiento> estado_movimiento { get; set; }
        public virtual ICollection<estado_proceso_item> estado_proceso_item { get; set; }
        public virtual ICollection<flujoxproceso> flujoxproceso { get; set; }
        public virtual ICollection<layout_flujo> layout_flujo { get; set; }
        public virtual ICollection<layout_linea_flujo> layout_linea_flujo { get; set; }
        public virtual linea linea { get; set; }
        public virtual ICollection<logcambia_estado> logcambia_estado { get; set; }
        public virtual ICollection<logcambia_estado> logcambia_estado1 { get; set; }
        public virtual ICollection<motivo_anulacion_proceso> motivo_anulacion_proceso { get; set; }
        public virtual ICollection<opciones> opciones { get; set; }
        public virtual ICollection<opciones> opciones1 { get; set; }
        public virtual ICollection<opciones_extra_proceso> opciones_extra_proceso { get; set; }
        public virtual ICollection<prioridad_movimiento> prioridad_movimiento { get; set; }
        public virtual ICollection<responsable_proceso> responsable_proceso { get; set; }
        public virtual ICollection<secuencia_proceso> secuencia_proceso { get; set; }
        public virtual ICollection<secuencia_proceso> secuencia_proceso1 { get; set; }
        public virtual ICollection<tipo_movimiento> tipo_movimiento { get; set; }
        public virtual ICollection<tipo_novedad> tipo_novedad { get; set; }
        public virtual ICollection<tipo_servicio> tipo_servicio { get; set; }
        public virtual ICollection<wcg_mapping> wcg_mapping { get; set; }
    }
}
