//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto_experiencia_contratoxcontrato_conmsumo
    {
        public int cod_producto_experiencia_contratoxcontrato_conmsumo { get; set; }
        public int cod_producto_experiencia_contrato { get; set; }
        public Nullable<int> cod_contratos_suministro { get; set; }
    
        public virtual contratos_suministro contratos_suministro { get; set; }
        public virtual producto_experiencia_contrato producto_experiencia_contrato { get; set; }
    }
}
