//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class programacionViajes
    {
        public programacionViajes()
        {
            this.detalleProgramacionViajes = new HashSet<detalleProgramacionViajes>();
        }
    
        public int codProgramacionViajes { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public string creadoPor { get; set; }
        public Nullable<System.DateTime> fechaViaje { get; set; }
        public Nullable<System.DateTime> fechaRegreso { get; set; }
        public string ingenieroAsignado { get; set; }
        public Nullable<bool> programada { get; set; }
        public string codPais { get; set; }
        public string codDepartamento { get; set; }
        public string codCiudad { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> codAsesor { get; set; }
    
        public virtual ICollection<detalleProgramacionViajes> detalleProgramacionViajes { get; set; }
    }
}
