//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedor
    {
        public proveedor()
        {
            this.movimiento = new HashSet<movimiento>();
        }
    
        public int cod_proveedor { get; set; }
        public Nullable<int> cod_linea { get; set; }
        public string nombre_proveedor { get; set; }
        public string direccion_proveedor { get; set; }
        public string telefono1_proveedor { get; set; }
        public string telefono2_proveedor { get; set; }
        public string contacto_proveedor { get; set; }
        public string email { get; set; }
    
        public virtual linea linea { get; set; }
        public virtual ICollection<movimiento> movimiento { get; set; }
    }
}
