//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class reactivo_solicitud
    {
        public int cod_reactivo_solicitud { get; set; }
        public int cod_solicitud_general { get; set; }
        public int cod_referencia_reactivo { get; set; }
        public Nullable<int> cod_asesoria_cientifica { get; set; }
    
        public virtual asesoria_cientifica asesoria_cientifica { get; set; }
        public virtual referencia_reactivo referencia_reactivo { get; set; }
        public virtual solicitud_general solicitud_general { get; set; }
    }
}
