//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class referencia_composicion
    {
        public int cod_referencia_composicion { get; set; }
        public string nombre_composicion { get; set; }
        public int cod_referencia_principal { get; set; }
        public int cod_referencia_componente { get; set; }
        public int cantidad { get; set; }
    
        public virtual referencia referencia { get; set; }
        public virtual referencia referencia1 { get; set; }
    }
}
