//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class regionesXusuarios
    {
        public string login { get; set; }
        public string codPais { get; set; }
        public string codDepartamento { get; set; }
        public string codCiudad { get; set; }
    
        public virtual ciudades ciudades { get; set; }
    }
}
