//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class repuestosxOrdenPrestamo
    {
        public int codOrdenPrestamo { get; set; }
        public string codRepuesto { get; set; }
        public Nullable<int> cantidadSolicitada { get; set; }
        public Nullable<int> cantidadPrestada { get; set; }
        public Nullable<int> cantidadDevuelta { get; set; }
        public Nullable<int> cantidadConNotaSalida { get; set; }
        public Nullable<bool> entregadoIngeniero { get; set; }
        public Nullable<bool> devueltoAlmacen { get; set; }
        public Nullable<bool> notaSalida { get; set; }
        public string obsNotaSalida { get; set; }
        public Nullable<System.DateTime> fechaEntregaIng { get; set; }
        public Nullable<System.DateTime> fechaDevolucion { get; set; }
        public Nullable<System.DateTime> fechaNotaSalida { get; set; }
    
        public virtual OrdenPrestamo OrdenPrestamo { get; set; }
        public virtual repuestos repuestos { get; set; }
    }
}
