//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class resultado_final_llamada
    {
        public int cod_resultado_final_llamada { get; set; }
        public string resultado_final_llamada1 { get; set; }
        public string abreviatura { get; set; }
    }
}
