//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class revision_equipos
    {
        public revision_equipos()
        {
            this.archivo_template_revision_equipo = new HashSet<archivo_template_revision_equipo>();
            this.archivos_revision_equipos = new HashSet<archivos_revision_equipos>();
        }
    
        public int cod_revision_equipos { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<int> cod_estado_revision_equipos { get; set; }
        public string serial { get; set; }
        public string codModelo { get; set; }
        public Nullable<int> ingeniero_entrega { get; set; }
        public Nullable<int> asesor_recibe { get; set; }
        public Nullable<bool> equipo_nuevo { get; set; }
        public string nit_cliente { get; set; }
        public string cod_sucursal { get; set; }
        public string observaciones_iniciales { get; set; }
        public string observaciones { get; set; }
        public Nullable<bool> adecuado { get; set; }
        public Nullable<int> responsable_revision { get; set; }
        public Nullable<int> responsable_aprobacion { get; set; }
        public Nullable<int> cod_origen_revision_equipos { get; set; }
        public string id_solicitud { get; set; }
        public Nullable<System.DateTime> fecha_revision { get; set; }
        public Nullable<System.DateTime> fecha_aprobacion { get; set; }
        public Nullable<System.DateTime> fecha_cierre { get; set; }
        public Nullable<int> cerrada_por { get; set; }
        public Nullable<int> cod_template_revison_equipo { get; set; }
        public Nullable<int> anulada_por { get; set; }
        public Nullable<System.DateTime> fecha_anulacion { get; set; }
        public string motivo_anulacion { get; set; }
        public Nullable<System.DateTime> fecha_programacion { get; set; }
        public Nullable<System.DateTime> fecha_fin_programacion { get; set; }
        public Nullable<System.DateTime> fecha_inicio_ejecucion { get; set; }
        public Nullable<System.DateTime> fecha_fin_ejecucion { get; set; }
        public Nullable<int> cod_orden_servicio { get; set; }
        public string nit_cliente_nuevo { get; set; }
        public string cod_sucursal_nuevo { get; set; }
    
        public virtual ICollection<archivo_template_revision_equipo> archivo_template_revision_equipo { get; set; }
        public virtual ICollection<archivos_revision_equipos> archivos_revision_equipos { get; set; }
        public virtual equipos equipos { get; set; }
        public virtual estado_revision_equipos estado_revision_equipos { get; set; }
        public virtual origen_revision_equipos origen_revision_equipos { get; set; }
        public virtual sucursalCliente sucursalCliente { get; set; }
        public virtual sucursalCliente sucursalCliente1 { get; set; }
        public virtual template_revison_equipo template_revison_equipo { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
        public virtual usuario usuario2 { get; set; }
        public virtual usuario usuario3 { get; set; }
    }
}
