//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class seguimiento
    {
        public int idSeguimiento { get; set; }
        public string creadoPor { get; set; }
        public Nullable<bool> realizado { get; set; }
        public string realizadoPor { get; set; }
        public Nullable<System.DateTime> fechaSugerida { get; set; }
        public Nullable<System.DateTime> fechaRealizado { get; set; }
        public string obsIniciales { get; set; }
        public string obsFinales { get; set; }
        public Nullable<int> idLlamadaSoporte { get; set; }
        public string nitCliente { get; set; }
        public string codContacto { get; set; }
        public string serial { get; set; }
    
        public virtual contactosClientes contactosClientes { get; set; }
        public virtual LlamadaSoporte LlamadaSoporte { get; set; }
    }
}
