//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class seguimiento_asesoria_cientifica
    {
        public seguimiento_asesoria_cientifica()
        {
            this.accion_seguirxseguimiento_cientifica = new HashSet<accion_seguirxseguimiento_cientifica>();
        }
    
        public int cod_seguimiento_asesoria_cientifica { get; set; }
        public System.DateTime fecha_seguimiento { get; set; }
        public string realizado_por { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> cod_asesoria_cientifica { get; set; }
        public string observaciones_tabla { get; set; }
    
        public virtual ICollection<accion_seguirxseguimiento_cientifica> accion_seguirxseguimiento_cientifica { get; set; }
    }
}
