//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class solicitud_general
    {
        public solicitud_general()
        {
            this.equipos_solicitud = new HashSet<equipos_solicitud>();
            this.reactivo_solicitud = new HashSet<reactivo_solicitud>();
            this.tipo_servicioxsolicitud = new HashSet<tipo_servicioxsolicitud>();
        }
    
        public int cod_solicitud_general { get; set; }
        public Nullable<int> cod_estado_solicitud_general { get; set; }
        public Nullable<int> creado_por { get; set; }
        public Nullable<int> aprobado_por { get; set; }
        public Nullable<int> ejecutado_por { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_aprobacion { get; set; }
        public Nullable<System.DateTime> fecha_ejecucion { get; set; }
        public string nitCliente { get; set; }
        public string codSucursal { get; set; }
        public string codContacto { get; set; }
        public Nullable<bool> contrato_legalizado { get; set; }
        public Nullable<bool> carta_aceptacion { get; set; }
        public Nullable<int> personas_entrenamiento { get; set; }
        public Nullable<System.DateTime> fechaIng { get; set; }
        public Nullable<System.DateTime> fechaCie { get; set; }
        public string observaciones { get; set; }
        public string observacionesAprobacion { get; set; }
        public Nullable<System.DateTime> cal1 { get; set; }
        public Nullable<System.DateTime> cal2 { get; set; }
        public Nullable<System.DateTime> cal3 { get; set; }
        public Nullable<System.DateTime> cal4 { get; set; }
        public Nullable<System.DateTime> cal5 { get; set; }
        public Nullable<decimal> num1 { get; set; }
        public Nullable<decimal> num2 { get; set; }
        public Nullable<decimal> num3 { get; set; }
        public Nullable<decimal> num4 { get; set; }
        public Nullable<decimal> num5 { get; set; }
        public string txt1 { get; set; }
        public string txt2 { get; set; }
        public string txt3 { get; set; }
        public string txt4 { get; set; }
        public string txt5 { get; set; }
        public Nullable<bool> ind1 { get; set; }
        public Nullable<bool> ind2 { get; set; }
        public Nullable<bool> ind3 { get; set; }
        public Nullable<bool> ind4 { get; set; }
        public Nullable<bool> ind5 { get; set; }
        public Nullable<bool> es_anulada { get; set; }
    
        public virtual contactosClientes contactosClientes { get; set; }
        public virtual ICollection<equipos_solicitud> equipos_solicitud { get; set; }
        public virtual estado_solicitud_general estado_solicitud_general { get; set; }
        public virtual ICollection<reactivo_solicitud> reactivo_solicitud { get; set; }
        public virtual sucursalCliente sucursalCliente { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
        public virtual usuario usuario2 { get; set; }
        public virtual ICollection<tipo_servicioxsolicitud> tipo_servicioxsolicitud { get; set; }
    }
}
