//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class spxReactivosValleEntities : DbContext
    {
        public spxReactivosValleEntities()
            : base("name=spxReactivosValleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<accesorio> accesorio { get; set; }
        public DbSet<accesoriosEquipo> accesoriosEquipo { get; set; }
        public DbSet<AccesoriosxEntradaSalidaEquipos> AccesoriosxEntradaSalidaEquipos { get; set; }
        public DbSet<accion_novedad> accion_novedad { get; set; }
        public DbSet<accion_seguir_cientifica> accion_seguir_cientifica { get; set; }
        public DbSet<accion_seguirxasesoria_cientifica> accion_seguirxasesoria_cientifica { get; set; }
        public DbSet<accion_seguirxseguimiento_cientifica> accion_seguirxseguimiento_cientifica { get; set; }
        public DbSet<actividad_adicional> actividad_adicional { get; set; }
        public DbSet<ActividadesxModelo> ActividadesxModelo { get; set; }
        public DbSet<actividadxordenServicio> actividadxordenServicio { get; set; }
        public DbSet<actividadxtarea_calendario> actividadxtarea_calendario { get; set; }
        public DbSet<adjunto_contrato_suministro> adjunto_contrato_suministro { get; set; }
        public DbSet<anuncio> anuncio { get; set; }
        public DbSet<archivo_movimiento> archivo_movimiento { get; set; }
        public DbSet<archivo_referencia> archivo_referencia { get; set; }
        public DbSet<archivo_template_revision_equipo> archivo_template_revision_equipo { get; set; }
        public DbSet<archivos_control_calidad> archivos_control_calidad { get; set; }
        public DbSet<archivos_revision_equipos> archivos_revision_equipos { get; set; }
        public DbSet<ArchivosxComponente> ArchivosxComponente { get; set; }
        public DbSet<archivosxcontrato> archivosxcontrato { get; set; }
        public DbSet<archivosxEntradaSalidaEquipos> archivosxEntradaSalidaEquipos { get; set; }
        public DbSet<archivosXequipo> archivosXequipo { get; set; }
        public DbSet<archivosxIncumplimiento> archivosxIncumplimiento { get; set; }
        public DbSet<archivosxModelo> archivosxModelo { get; set; }
        public DbSet<archivosXOrdenServicio> archivosXOrdenServicio { get; set; }
        public DbSet<archivosxRepuesto> archivosxRepuesto { get; set; }
        public DbSet<archivosxtarea_calendario> archivosxtarea_calendario { get; set; }
        public DbSet<archivoxcontrato_consumo> archivoxcontrato_consumo { get; set; }
        public DbSet<archivoxcontratos_suministro> archivoxcontratos_suministro { get; set; }
        public DbSet<asesoresComerciales> asesoresComerciales { get; set; }
        public DbSet<asesoria_cientifica> asesoria_cientifica { get; set; }
        public DbSet<asistente_capacitacion> asistente_capacitacion { get; set; }
        public DbSet<asistentexsession> asistentexsession { get; set; }
        public DbSet<auditoria> auditoria { get; set; }
        public DbSet<bodega> bodega { get; set; }
        public DbSet<calibracion_calidad> calibracion_calidad { get; set; }
        public DbSet<campos_template_revision> campos_template_revision { get; set; }
        public DbSet<capacitacion> capacitacion { get; set; }
        public DbSet<categoria_referencia> categoria_referencia { get; set; }
        public DbSet<cgq_layout_pivote> cgq_layout_pivote { get; set; }
        public DbSet<cgq_parametrosquery> cgq_parametrosquery { get; set; }
        public DbSet<cgq_parametrosquery_ultimo_valor> cgq_parametrosquery_ultimo_valor { get; set; }
        public DbSet<cgq_query> cgq_query { get; set; }
        public DbSet<cgq_queryxgrupo_usuario> cgq_queryxgrupo_usuario { get; set; }
        public DbSet<cgq_queryxusuario> cgq_queryxusuario { get; set; }
        public DbSet<cgq_tablas_pivote> cgq_tablas_pivote { get; set; }
        public DbSet<ciudad> ciudad { get; set; }
        public DbSet<ciudades> ciudades { get; set; }
        public DbSet<cliente> cliente { get; set; }
        public DbSet<clientes> clientes { get; set; }
        public DbSet<componente> componente { get; set; }
        public DbSet<comprobantesAceptacionOrdenservicio> comprobantesAceptacionOrdenservicio { get; set; }
        public DbSet<confirmacion_evento> confirmacion_evento { get; set; }
        public DbSet<consumibles> consumibles { get; set; }
        public DbSet<consumiblexcontrato_consumo> consumiblexcontrato_consumo { get; set; }
        public DbSet<consumoContratoxLinea> consumoContratoxLinea { get; set; }
        public DbSet<consumosxContratos> consumosxContratos { get; set; }
        public DbSet<contacto_cliente> contacto_cliente { get; set; }
        public DbSet<contactosClientes> contactosClientes { get; set; }
        public DbSet<contrato_consumo> contrato_consumo { get; set; }
        public DbSet<contratos> contratos { get; set; }
        public DbSet<contratos_suministro> contratos_suministro { get; set; }
        public DbSet<contratosxEquipo> contratosxEquipo { get; set; }
        public DbSet<control_calidad> control_calidad { get; set; }
        public DbSet<control_calidad_interno> control_calidad_interno { get; set; }
        public DbSet<controles_calidad> controles_calidad { get; set; }
        public DbSet<departamento> departamento { get; set; }
        public DbSet<departamentos> departamentos { get; set; }
        public DbSet<detalle_movimiento> detalle_movimiento { get; set; }
        public DbSet<detalleProgramacionViajes> detalleProgramacionViajes { get; set; }
        public DbSet<detalleSolicitudInsumos> detalleSolicitudInsumos { get; set; }
        public DbSet<dias_festivos> dias_festivos { get; set; }
        public DbSet<dispositivosmedicionxordenservicio> dispositivosmedicionxordenservicio { get; set; }
        public DbSet<division_experiencia_contrato_suministro> division_experiencia_contrato_suministro { get; set; }
        public DbSet<divisionxcontrato_suministro> divisionxcontrato_suministro { get; set; }
        public DbSet<dominio> dominio { get; set; }
        public DbSet<EntradaSalidaEquipos> EntradaSalidaEquipos { get; set; }
        public DbSet<equipoAuxiliar> equipoAuxiliar { get; set; }
        public DbSet<equipos> equipos { get; set; }
        public DbSet<equipos_solicitud> equipos_solicitud { get; set; }
        public DbSet<equiposAuxiliaresxEntrada> equiposAuxiliaresxEntrada { get; set; }
        public DbSet<equiposxcontrato_consumo> equiposxcontrato_consumo { get; set; }
        public DbSet<estado_adjunto_contrato_suministro> estado_adjunto_contrato_suministro { get; set; }
        public DbSet<estado_asesoria_cientifica> estado_asesoria_cientifica { get; set; }
        public DbSet<estado_bloqueo> estado_bloqueo { get; set; }
        public DbSet<estado_capacitacion> estado_capacitacion { get; set; }
        public DbSet<estado_contrato_suministro> estado_contrato_suministro { get; set; }
        public DbSet<estado_control_calidad> estado_control_calidad { get; set; }
        public DbSet<estado_fisico> estado_fisico { get; set; }
        public DbSet<estado_movimiento> estado_movimiento { get; set; }
        public DbSet<estado_movimientoxgrupo_usuario> estado_movimientoxgrupo_usuario { get; set; }
        public DbSet<estado_movimientoxusuario> estado_movimientoxusuario { get; set; }
        public DbSet<estado_proceso_item> estado_proceso_item { get; set; }
        public DbSet<estado_revision_equipos> estado_revision_equipos { get; set; }
        public DbSet<estado_solicitud_general> estado_solicitud_general { get; set; }
        public DbSet<estado_tarea_calendario> estado_tarea_calendario { get; set; }
        public DbSet<EstadoFisicamente> EstadoFisicamente { get; set; }
        public DbSet<estadoLocalEquipos> estadoLocalEquipos { get; set; }
        public DbSet<estadoRecoleccion> estadoRecoleccion { get; set; }
        public DbSet<estadosLLamadasTecnicas> estadosLLamadasTecnicas { get; set; }
        public DbSet<estadosOrdenPrestamo> estadosOrdenPrestamo { get; set; }
        public DbSet<estadosOrdenServicio> estadosOrdenServicio { get; set; }
        public DbSet<estadosSolicitud> estadosSolicitud { get; set; }
        public DbSet<estampillas_contrato_sumisnistro> estampillas_contrato_sumisnistro { get; set; }
        public DbSet<existencia> existencia { get; set; }
        public DbSet<fabricante> fabricante { get; set; }
        public DbSet<filtro_estado_movimiento> filtro_estado_movimiento { get; set; }
        public DbSet<Firma> Firma { get; set; }
        public DbSet<flujo> flujo { get; set; }
        public DbSet<flujoxestado> flujoxestado { get; set; }
        public DbSet<flujoxproceso> flujoxproceso { get; set; }
        public DbSet<fotografia> fotografia { get; set; }
        public DbSet<funcionalidad> funcionalidad { get; set; }
        public DbSet<funcionalidad_grupousuario> funcionalidad_grupousuario { get; set; }
        public DbSet<funcionalidad_usuario> funcionalidad_usuario { get; set; }
        public DbSet<grupo_consumible> grupo_consumible { get; set; }
        public DbSet<grupo_inventario> grupo_inventario { get; set; }
        public DbSet<grupo_reactivo_experiencia> grupo_reactivo_experiencia { get; set; }
        public DbSet<grupo_reactivoxcontrato_suministro> grupo_reactivoxcontrato_suministro { get; set; }
        public DbSet<grupo_usuario> grupo_usuario { get; set; }
        public DbSet<grupo_usuarioxlinea> grupo_usuarioxlinea { get; set; }
        public DbSet<gruposLineasConsumo> gruposLineasConsumo { get; set; }
        public DbSet<gruposModulos> gruposModulos { get; set; }
        public DbSet<gruposModulosxGruposUsuarios> gruposModulosxGruposUsuarios { get; set; }
        public DbSet<gruposUsuarios> gruposUsuarios { get; set; }
        public DbSet<gruposUsuariosxUsuario> gruposUsuariosxUsuario { get; set; }
        public DbSet<grupousuario_usuario> grupousuario_usuario { get; set; }
        public DbSet<inconveniente_presentado_cientifica> inconveniente_presentado_cientifica { get; set; }
        public DbSet<incrementosxlinea_consumo> incrementosxlinea_consumo { get; set; }
        public DbSet<incumplimientoConsumo> incumplimientoConsumo { get; set; }
        public DbSet<indicacionesLLamadas> indicacionesLLamadas { get; set; }
        public DbSet<informacion_adicional_usuario> informacion_adicional_usuario { get; set; }
        public DbSet<informacion_extendida_detalle> informacion_extendida_detalle { get; set; }
        public DbSet<informacion_extendida_movimiento> informacion_extendida_movimiento { get; set; }
        public DbSet<layout_flujo> layout_flujo { get; set; }
        public DbSet<layout_linea_flujo> layout_linea_flujo { get; set; }
        public DbSet<linea> linea { get; set; }
        public DbSet<linea_consumo> linea_consumo { get; set; }
        public DbSet<linea_consumoxcontrato_consumo> linea_consumoxcontrato_consumo { get; set; }
        public DbSet<lineasConsumo> lineasConsumo { get; set; }
        public DbSet<lineasxusuario> lineasxusuario { get; set; }
        public DbSet<LlamadaSoporte> LlamadaSoporte { get; set; }
        public DbSet<LlamadaSoportePre> LlamadaSoportePre { get; set; }
        public DbSet<log_cambio_contratos_consumo> log_cambio_contratos_consumo { get; set; }
        public DbSet<log_cambios_estado_contratos_suministro> log_cambios_estado_contratos_suministro { get; set; }
        public DbSet<logcambia_estado> logcambia_estado { get; set; }
        public DbSet<logCambioUbicaciones> logCambioUbicaciones { get; set; }
        public DbSet<logVinculacionesDesvinculacionesContrato> logVinculacionesDesvinculacionesContrato { get; set; }
        public DbSet<mantenimientosxContrato> mantenimientosxContrato { get; set; }
        public DbSet<medioSolicitud> medioSolicitud { get; set; }
        public DbSet<modalidad> modalidad { get; set; }
        public DbSet<modalidad_contrato> modalidad_contrato { get; set; }
        public DbSet<modalidadContrato> modalidadContrato { get; set; }
        public DbSet<ModalidadEquipo> ModalidadEquipo { get; set; }
        public DbSet<modelo_inventario> modelo_inventario { get; set; }
        public DbSet<Modelos> Modelos { get; set; }
        public DbSet<modeloxtarea> modeloxtarea { get; set; }
        public DbSet<modulo_seguridad> modulo_seguridad { get; set; }
        public DbSet<moduloseguridad_grupousuario> moduloseguridad_grupousuario { get; set; }
        public DbSet<moduloseguridad_usuario> moduloseguridad_usuario { get; set; }
        public DbSet<motivo_anulacion_cientifica> motivo_anulacion_cientifica { get; set; }
        public DbSet<motivo_anulacion_movimiento> motivo_anulacion_movimiento { get; set; }
        public DbSet<motivo_anulacion_proceso> motivo_anulacion_proceso { get; set; }
        public DbSet<motivo_anulacion_suministro> motivo_anulacion_suministro { get; set; }
        public DbSet<motivo_no_renovacion> motivo_no_renovacion { get; set; }
        public DbSet<motivo_salida> motivo_salida { get; set; }
        public DbSet<movimiento> movimiento { get; set; }
        public DbSet<muelle> muelle { get; set; }
        public DbSet<notificacion> notificacion { get; set; }
        public DbSet<notificacion_estado> notificacion_estado { get; set; }
        public DbSet<notificacion_estado_copia_grupo> notificacion_estado_copia_grupo { get; set; }
        public DbSet<notificacion_estado_copia_usuario> notificacion_estado_copia_usuario { get; set; }
        public DbSet<novedad_movimiento> novedad_movimiento { get; set; }
        public DbSet<ObservacionesxOrdenPrestamo> ObservacionesxOrdenPrestamo { get; set; }
        public DbSet<observicionesxseguimiento_control_calidad> observicionesxseguimiento_control_calidad { get; set; }
        public DbSet<opciones> opciones { get; set; }
        public DbSet<opciones_extra_proceso> opciones_extra_proceso { get; set; }
        public DbSet<OrdenPrestamo> OrdenPrestamo { get; set; }
        public DbSet<ordenServicio> ordenServicio { get; set; }
        public DbSet<origen_datos> origen_datos { get; set; }
        public DbSet<origen_revision_equipos> origen_revision_equipos { get; set; }
        public DbSet<pais> pais { get; set; }
        public DbSet<paises> paises { get; set; }
        public DbSet<parametro> parametro { get; set; }
        public DbSet<parametro_cientifica> parametro_cientifica { get; set; }
        public DbSet<pendiente_tarea> pendiente_tarea { get; set; }
        public DbSet<polizas_contrato_suministro> polizas_contrato_suministro { get; set; }
        public DbSet<preime_referencia> preime_referencia { get; set; }
        public DbSet<prioridad> prioridad { get; set; }
        public DbSet<prioridad_callcenter_cientifica> prioridad_callcenter_cientifica { get; set; }
        public DbSet<prioridad_movimiento> prioridad_movimiento { get; set; }
        public DbSet<prioridadesOrdenServicio> prioridadesOrdenServicio { get; set; }
        public DbSet<prioridadSolicitud> prioridadSolicitud { get; set; }
        public DbSet<problemas_comunes_cientifica> problemas_comunes_cientifica { get; set; }
        public DbSet<problemas_frecuentes> problemas_frecuentes { get; set; }
        public DbSet<problemas_frecuentes_por_llamada> problemas_frecuentes_por_llamada { get; set; }
        public DbSet<proceso> proceso { get; set; }
        public DbSet<producto_experiencia_contrato> producto_experiencia_contrato { get; set; }
        public DbSet<producto_experiencia_contratoxcontrato_conmsumo> producto_experiencia_contratoxcontrato_conmsumo { get; set; }
        public DbSet<programacionViajes> programacionViajes { get; set; }
        public DbSet<proveedor> proveedor { get; set; }
        public DbSet<razon_no_vigente> razon_no_vigente { get; set; }
        public DbSet<reactivo_solicitud> reactivo_solicitud { get; set; }
        public DbSet<reactivoxtarea> reactivoxtarea { get; set; }
        public DbSet<reasignacionOrdenesTrabajo> reasignacionOrdenesTrabajo { get; set; }
        public DbSet<recoleccion> recoleccion { get; set; }
        public DbSet<referencia> referencia { get; set; }
        public DbSet<referencia_composicion> referencia_composicion { get; set; }
        public DbSet<referencia_reactivo> referencia_reactivo { get; set; }
        public DbSet<regionesXusuarios> regionesXusuarios { get; set; }
        public DbSet<repuestos> repuestos { get; set; }
        public DbSet<repuestosxContratos> repuestosxContratos { get; set; }
        public DbSet<repuestosxOrdenPrestamo> repuestosxOrdenPrestamo { get; set; }
        public DbSet<repuestoxOrdenServicio> repuestoxOrdenServicio { get; set; }
        public DbSet<responsable_proceso> responsable_proceso { get; set; }
        public DbSet<resultado_final_llamada> resultado_final_llamada { get; set; }
        public DbSet<revision_equipos> revision_equipos { get; set; }
        public DbSet<revision_estado_producto> revision_estado_producto { get; set; }
        public DbSet<rpt> rpt { get; set; }
        public DbSet<rpt_grupousuario> rpt_grupousuario { get; set; }
        public DbSet<secuencia_estado_movimiento> secuencia_estado_movimiento { get; set; }
        public DbSet<secuencia_proceso> secuencia_proceso { get; set; }
        public DbSet<seguimiento> seguimiento { get; set; }
        public DbSet<seguimiento_asesoria_cientifica> seguimiento_asesoria_cientifica { get; set; }
        public DbSet<session_capacitacion> session_capacitacion { get; set; }
        public DbSet<solicitud_general> solicitud_general { get; set; }
        public DbSet<solicitudInsumos> solicitudInsumos { get; set; }
        public DbSet<solicitudServicio> solicitudServicio { get; set; }
        public DbSet<soluciones_problemas> soluciones_problemas { get; set; }
        public DbSet<sub_modalidad_contrato> sub_modalidad_contrato { get; set; }
        public DbSet<sub_tipo_tarea_calendario> sub_tipo_tarea_calendario { get; set; }
        public DbSet<sub_variable_medicion> sub_variable_medicion { get; set; }
        public DbSet<subcategoria_referencia> subcategoria_referencia { get; set; }
        public DbSet<subCategoriaComponente> subCategoriaComponente { get; set; }
        public DbSet<subTipoComponente> subTipoComponente { get; set; }
        public DbSet<subTipoEquipo> subTipoEquipo { get; set; }
        public DbSet<sucursal_cliente> sucursal_cliente { get; set; }
        public DbSet<sucursalCliente> sucursalCliente { get; set; }
        public DbSet<sucursalxcontacto> sucursalxcontacto { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<sysusersobjects> sysusersobjects { get; set; }
        public DbSet<tarea_asesoria_cientifica> tarea_asesoria_cientifica { get; set; }
        public DbSet<tarea_calendario> tarea_calendario { get; set; }
        public DbSet<task> task { get; set; }
        public DbSet<taskAdjuntos> taskAdjuntos { get; set; }
        public DbSet<taskCategoria> taskCategoria { get; set; }
        public DbSet<taskEstatus> taskEstatus { get; set; }
        public DbSet<taskPatronRecurrencia> taskPatronRecurrencia { get; set; }
        public DbSet<TaskReminder> TaskReminder { get; set; }
        public DbSet<template_revison_equipo> template_revison_equipo { get; set; }
        public DbSet<tipo_actividad> tipo_actividad { get; set; }
        public DbSet<tipo_actividadxsubtipo_tarea_calendario> tipo_actividadxsubtipo_tarea_calendario { get; set; }
        public DbSet<tipo_adjunto_contrato_suministro> tipo_adjunto_contrato_suministro { get; set; }
        public DbSet<tipo_archivo> tipo_archivo { get; set; }
        public DbSet<tipo_asesoria> tipo_asesoria { get; set; }
        public DbSet<tipo_bodega> tipo_bodega { get; set; }
        public DbSet<tipo_documento> tipo_documento { get; set; }
        public DbSet<tipo_estado_bloqueo> tipo_estado_bloqueo { get; set; }
        public DbSet<tipo_estado_fisico> tipo_estado_fisico { get; set; }
        public DbSet<tipo_movimiento> tipo_movimiento { get; set; }
        public DbSet<tipo_novedad> tipo_novedad { get; set; }
        public DbSet<tipo_propiedad> tipo_propiedad { get; set; }
        public DbSet<tipo_servicio> tipo_servicio { get; set; }
        public DbSet<tipo_servicioxsolicitud> tipo_servicioxsolicitud { get; set; }
        public DbSet<tipo_software_contrato_consumo> tipo_software_contrato_consumo { get; set; }
        public DbSet<tipo_softwarexcontrato_consumo> tipo_softwarexcontrato_consumo { get; set; }
        public DbSet<tipo_tarea_calendario> tipo_tarea_calendario { get; set; }
        public DbSet<tipoarchivoxcontratos_suministro> tipoarchivoxcontratos_suministro { get; set; }
        public DbSet<TipoCombo> TipoCombo { get; set; }
        public DbSet<tipoComponente> tipoComponente { get; set; }
        public DbSet<tipoComprobante> tipoComprobante { get; set; }
        public DbSet<tipoContrato> tipoContrato { get; set; }
        public DbSet<tipoDocumento> tipoDocumento { get; set; }
        public DbSet<tipoEquipo> tipoEquipo { get; set; }
        public DbSet<tipofiltro_query_rpt> tipofiltro_query_rpt { get; set; }
        public DbSet<tipoPropiedad> tipoPropiedad { get; set; }
        public DbSet<TiposArchivoXequipo> TiposArchivoXequipo { get; set; }
        public DbSet<TipoServicio> TipoServicio { get; set; }
        public DbSet<titulo_persona> titulo_persona { get; set; }
        public DbSet<tituloContacto> tituloContacto { get; set; }
        public DbSet<trabajosxReporteServicio> trabajosxReporteServicio { get; set; }
        public DbSet<transportador> transportador { get; set; }
        public DbSet<transportadora> transportadora { get; set; }
        public DbSet<ubicacion> ubicacion { get; set; }
        public DbSet<ubicacion_por_referencia> ubicacion_por_referencia { get; set; }
        public DbSet<ubicacionesxbodega_fisica> ubicacionesxbodega_fisica { get; set; }
        public DbSet<ubicacionxestado_bloqueo> ubicacionxestado_bloqueo { get; set; }
        public DbSet<ubicacionxestado_fisico> ubicacionxestado_fisico { get; set; }
        public DbSet<ubicacionxgrupo_inventario> ubicacionxgrupo_inventario { get; set; }
        public DbSet<unidad_empaque> unidad_empaque { get; set; }
        public DbSet<unidad_medida> unidad_medida { get; set; }
        public DbSet<unidad_peso> unidad_peso { get; set; }
        public DbSet<unidad_tiempo> unidad_tiempo { get; set; }
        public DbSet<unidadPeso> unidadPeso { get; set; }
        public DbSet<unidadTiempo> unidadTiempo { get; set; }
        public DbSet<usuario> usuario { get; set; }
        public DbSet<variables_medicion> variables_medicion { get; set; }
        public DbSet<variables_medicionxmodelo> variables_medicionxmodelo { get; set; }
        public DbSet<variables_medicionxorden_servicio> variables_medicionxorden_servicio { get; set; }
        public DbSet<vigencias_contrato_consumo> vigencias_contrato_consumo { get; set; }
        public DbSet<wcg_mapping> wcg_mapping { get; set; }
        public DbSet<wcg_smtp_adjuntos> wcg_smtp_adjuntos { get; set; }
        public DbSet<wcg_smtp_email> wcg_smtp_email { get; set; }
        public DbSet<wcg_smtp_email_cc> wcg_smtp_email_cc { get; set; }
        public DbSet<wcg_smtp_email_to> wcg_smtp_email_to { get; set; }
        public DbSet<wcg_smtp_email_to_cco> wcg_smtp_email_to_cco { get; set; }
        public DbSet<wcg_smtp_server> wcg_smtp_server { get; set; }
        public DbSet<wcg_smtp_server_cc> wcg_smtp_server_cc { get; set; }
        public DbSet<wcg_smtp_server_cco> wcg_smtp_server_cco { get; set; }
        public DbSet<wcg_virtual_field> wcg_virtual_field { get; set; }
        public DbSet<wcg_virtual_frm> wcg_virtual_frm { get; set; }
        public DbSet<wcg_virtual_grp> wcg_virtual_grp { get; set; }
        public DbSet<wcg_virtual_tab> wcg_virtual_tab { get; set; }
        public DbSet<vistaEquipo> vistaEquipo { get; set; }
        public DbSet<vistaSucursal> vistaSucursal { get; set; }
    
        public virtual ObjectResult<calendario_Result> calendario(Nullable<int> usuario, Nullable<System.DateTime> rangoinicial, Nullable<System.DateTime> rangofinal)
        {
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(int));
    
            var rangoinicialParameter = rangoinicial.HasValue ?
                new ObjectParameter("rangoinicial", rangoinicial) :
                new ObjectParameter("rangoinicial", typeof(System.DateTime));
    
            var rangofinalParameter = rangofinal.HasValue ?
                new ObjectParameter("rangofinal", rangofinal) :
                new ObjectParameter("rangofinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<calendario_Result>("calendario", usuarioParameter, rangoinicialParameter, rangofinalParameter);
        }
    }
}
