//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sub_tipo_tarea_calendario
    {
        public sub_tipo_tarea_calendario()
        {
            this.tarea_calendario = new HashSet<tarea_calendario>();
            this.tipo_actividadxsubtipo_tarea_calendario = new HashSet<tipo_actividadxsubtipo_tarea_calendario>();
        }
    
        public int cod_subtipo_tarea_calendario { get; set; }
        public int cod_tipo_tarea_calendario { get; set; }
        public string descripcion { get; set; }
        public string url { get; set; }
        public bool activo { get; set; }
    
        public virtual tipo_tarea_calendario tipo_tarea_calendario { get; set; }
        public virtual ICollection<tarea_calendario> tarea_calendario { get; set; }
        public virtual ICollection<tipo_actividadxsubtipo_tarea_calendario> tipo_actividadxsubtipo_tarea_calendario { get; set; }
    }
}
