//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class subTipoComponente
    {
        public subTipoComponente()
        {
            this.subCategoriaComponente = new HashSet<subCategoriaComponente>();
        }
    
        public string codTipoComponente { get; set; }
        public string codSubTipoCom { get; set; }
        public string nombreSubTipocom { get; set; }
    
        public virtual ICollection<subCategoriaComponente> subCategoriaComponente { get; set; }
        public virtual tipoComponente tipoComponente { get; set; }
    }
}
