//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sucursalxcontacto
    {
        public int cod_sucursalxcontacto { get; set; }
        public int cod_contacto_cliente { get; set; }
        public int cod_sucursal_cliente { get; set; }
    
        public virtual contacto_cliente contacto_cliente { get; set; }
        public virtual sucursal_cliente sucursal_cliente { get; set; }
    }
}
