//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysusersobjects
    {
        public string name { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string user_ { get; set; }
        public string object_ { get; set; }
        public string file_ { get; set; }
        public string file_size { get; set; }
        public string file_date { get; set; }
        public string file_time { get; set; }
        public string pointer { get; set; }
        public Nullable<int> id_user { get; set; }
        public int idSysuserObjects { get; set; }
    }
}
