//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class taskPatronRecurrencia
    {
        public int codTarea { get; set; }
        public int codPatron { get; set; }
        public Nullable<bool> diaria { get; set; }
        public Nullable<bool> diariaCada { get; set; }
        public Nullable<int> diariaCadaDias { get; set; }
        public Nullable<bool> diariaSemanal { get; set; }
        public Nullable<bool> semanal { get; set; }
        public Nullable<bool> semLunes { get; set; }
        public Nullable<bool> semMartes { get; set; }
        public Nullable<bool> semMiercoles { get; set; }
        public Nullable<bool> semJueves { get; set; }
        public Nullable<bool> semViernes { get; set; }
        public Nullable<bool> semSabado { get; set; }
        public Nullable<bool> semDomingo { get; set; }
        public Nullable<bool> Mensual { get; set; }
        public Nullable<bool> menElDia { get; set; }
        public Nullable<int> menEldiaDia { get; set; }
        public Nullable<int> menEldiaCada { get; set; }
        public Nullable<bool> menEl { get; set; }
        public string menElOrdenDia { get; set; }
        public string menElNombreDia { get; set; }
        public Nullable<int> menElCada { get; set; }
        public Nullable<bool> anual { get; set; }
        public Nullable<bool> anuCada { get; set; }
        public string anuCadaMes { get; set; }
        public string anuCadaDia { get; set; }
        public Nullable<bool> anuEl { get; set; }
        public string anuElOrden { get; set; }
        public string anuElDia { get; set; }
        public string anuElMes { get; set; }
        public Nullable<System.DateTime> inicia { get; set; }
        public Nullable<bool> sinFechaFin { get; set; }
        public Nullable<bool> finalizaDespues { get; set; }
        public Nullable<int> finalizaOcurrencias { get; set; }
        public Nullable<bool> finalizaElDia { get; set; }
        public Nullable<System.DateTime> finalizaDia { get; set; }
        public Nullable<System.DateTime> ultimoAviso { get; set; }
    
        public virtual task task { get; set; }
    }
}
