//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public task()
        {
            this.taskAdjuntos = new HashSet<taskAdjuntos>();
            this.taskPatronRecurrencia = new HashSet<taskPatronRecurrencia>();
            this.TaskReminder = new HashSet<TaskReminder>();
        }
    
        public int codTarea { get; set; }
        public string loginAutor { get; set; }
        public string codCategoria { get; set; }
        public string loginPropietario { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaVencimiento { get; set; }
        public string codEstatus { get; set; }
        public string codPrioridad { get; set; }
        public Nullable<int> pcCompletado { get; set; }
        public string asunto { get; set; }
        public string cuerpo { get; set; }
        public Nullable<bool> esCompletada { get; set; }
        public Nullable<bool> esAprobada { get; set; }
        public Nullable<bool> conservarEnPropias { get; set; }
        public Nullable<bool> notificarFin { get; set; }
        public Nullable<bool> esPrivada { get; set; }
        public Nullable<int> codTareaCompartida { get; set; }
        public Nullable<bool> aceptada { get; set; }
        public string asociadoA { get; set; }
        public Nullable<System.DateTime> fechaFinalizacion { get; set; }
        public Nullable<System.DateTime> fechaAprobacion { get; set; }
        public Nullable<bool> visibleAutor { get; set; }
        public Nullable<bool> visiblePropietario { get; set; }
        public string parametrosInternos { get; set; }
    
        public virtual prioridad prioridad { get; set; }
        public virtual taskCategoria taskCategoria { get; set; }
        public virtual taskEstatus taskEstatus { get; set; }
        public virtual ICollection<taskAdjuntos> taskAdjuntos { get; set; }
        public virtual ICollection<taskPatronRecurrencia> taskPatronRecurrencia { get; set; }
        public virtual ICollection<TaskReminder> TaskReminder { get; set; }
    }
}
