//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class taskEstatus
    {
        public taskEstatus()
        {
            this.task = new HashSet<task>();
        }
    
        public string codEstatus { get; set; }
        public string nombreEstatus { get; set; }
        public string DescripcionEstatus { get; set; }
        public Nullable<bool> indFin { get; set; }
        public Nullable<bool> IndIni { get; set; }
    
        public virtual ICollection<task> task { get; set; }
    }
}
