//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class template_revison_equipo
    {
        public template_revison_equipo()
        {
            this.campos_template_revision = new HashSet<campos_template_revision>();
            this.revision_equipos = new HashSet<revision_equipos>();
        }
    
        public int cod_template_revison_equipo { get; set; }
        public string version_template_revison_equipo { get; set; }
        public string codFabricante { get; set; }
        public string codModelo { get; set; }
        public Nullable<System.DateTime> vigencia_desde { get; set; }
        public Nullable<System.DateTime> vigencia_hasta { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> creado_por { get; set; }
        public string observaciones_ajustes { get; set; }
        public byte[] archivo_template { get; set; }
        public string nombre_archivo { get; set; }
    
        public virtual ICollection<campos_template_revision> campos_template_revision { get; set; }
        public virtual Modelos Modelos { get; set; }
        public virtual ICollection<revision_equipos> revision_equipos { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
