//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_actividadxsubtipo_tarea_calendario
    {
        public tipo_actividadxsubtipo_tarea_calendario()
        {
            this.actividadxtarea_calendario = new HashSet<actividadxtarea_calendario>();
        }
    
        public int cod_tipo_actividadxsubtipo_tarea_calendario { get; set; }
        public int cod_subtipo_tarea_calendario { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual ICollection<actividadxtarea_calendario> actividadxtarea_calendario { get; set; }
        public virtual sub_tipo_tarea_calendario sub_tipo_tarea_calendario { get; set; }
    }
}
