//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_documento
    {
        public tipo_documento()
        {
            this.contacto_cliente = new HashSet<contacto_cliente>();
            this.usuario = new HashSet<usuario>();
        }
    
        public int cod_tipo_documento { get; set; }
        public string nombre_tipo_documento { get; set; }
        public Nullable<bool> ind_1 { get; set; }
        public Nullable<bool> ind_2 { get; set; }
        public string abreviatura { get; set; }
    
        public virtual ICollection<contacto_cliente> contacto_cliente { get; set; }
        public virtual ICollection<usuario> usuario { get; set; }
    }
}
