//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_movimiento
    {
        public tipo_movimiento()
        {
            this.movimiento = new HashSet<movimiento>();
        }
    
        public int cod_tipo_movimiento { get; set; }
        public string nombre_tipo_movimiento { get; set; }
        public Nullable<int> cod_proceso { get; set; }
    
        public virtual ICollection<movimiento> movimiento { get; set; }
        public virtual proceso proceso { get; set; }
    }
}
