//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipoEquipo
    {
        public tipoEquipo()
        {
            this.subTipoEquipo = new HashSet<subTipoEquipo>();
        }
    
        public string codTipoEquipo { get; set; }
        public string nombreTipoEquipo { get; set; }
        public Nullable<bool> dispositivo_medicion { get; set; }
        public Nullable<bool> dispositivo_medible { get; set; }
        public Nullable<bool> omite_aprobacion_os { get; set; }
    
        public virtual ICollection<subTipoEquipo> subTipoEquipo { get; set; }
    }
}
