//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_estado_bloqueo
    {
        public tipo_estado_bloqueo()
        {
            this.estado_bloqueo = new HashSet<estado_bloqueo>();
        }
    
        public int cod_tipo_estado_bloqueo { get; set; }
        public string nombre_estado_bloqueo { get; set; }
        public Nullable<int> cod_linea { get; set; }
    
        public virtual ICollection<estado_bloqueo> estado_bloqueo { get; set; }
        public virtual linea linea { get; set; }
    }
}
