//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipoarchivoxcontratos_suministro
    {
        public tipoarchivoxcontratos_suministro()
        {
            this.archivoxcontratos_suministro = new HashSet<archivoxcontratos_suministro>();
        }
    
        public int cod_tipoarchivoxcontratos_suministro { get; set; }
        public string nombre_archivoxcontratos_suministro { get; set; }
    
        public virtual ICollection<archivoxcontratos_suministro> archivoxcontratos_suministro { get; set; }
    }
}
