//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoServicio
    {
        public TipoServicio()
        {
            this.EntradaSalidaEquipos = new HashSet<EntradaSalidaEquipos>();
            this.equipos = new HashSet<equipos>();
            this.ordenServicio = new HashSet<ordenServicio>();
            this.solicitudServicio = new HashSet<solicitudServicio>();
        }
    
        public string codTipoServicio { get; set; }
        public string nombretipoServicio { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> devuelveTaller { get; set; }
        public Nullable<bool> validoContrato { get; set; }
        public Nullable<bool> preventivo { get; set; }
        public Nullable<bool> correctivo { get; set; }
        public Nullable<bool> devuelveEntrada { get; set; }
        public Nullable<bool> omite_aprobacion_os { get; set; }
    
        public virtual ICollection<EntradaSalidaEquipos> EntradaSalidaEquipos { get; set; }
        public virtual ICollection<equipos> equipos { get; set; }
        public virtual ICollection<ordenServicio> ordenServicio { get; set; }
        public virtual ICollection<solicitudServicio> solicitudServicio { get; set; }
    }
}
