//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_archivo
    {
        public tipo_archivo()
        {
            this.archivo_movimiento = new HashSet<archivo_movimiento>();
        }
    
        public int cod_tipo_archivo { get; set; }
        public int cod_linea { get; set; }
        public string nombre_tipo_archivo { get; set; }
    
        public virtual ICollection<archivo_movimiento> archivo_movimiento { get; set; }
        public virtual linea linea { get; set; }
    }
}
