//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipoComprobante
    {
        public tipoComprobante()
        {
            this.comprobantesAceptacionOrdenservicio = new HashSet<comprobantesAceptacionOrdenservicio>();
        }
    
        public string codTipoComprobante { get; set; }
        public string NombreTipoComprobante { get; set; }
    
        public virtual ICollection<comprobantesAceptacionOrdenservicio> comprobantesAceptacionOrdenservicio { get; set; }
    }
}
