//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class trabajosxReporteServicio
    {
        public int idReporteServicio { get; set; }
        public int idTrabajo { get; set; }
        public string loginAutor { get; set; }
        public string descripcion { get; set; }
    }
}
