//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ubicacionxgrupo_inventario
    {
        public int cod_ubicacionxgrupo_inventario { get; set; }
        public int cod_ubicacion { get; set; }
        public int cod_grupo_inventario { get; set; }
    
        public virtual grupo_inventario grupo_inventario { get; set; }
        public virtual ubicacion ubicacion { get; set; }
    }
}
