//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ubicacion
    {
        public ubicacion()
        {
            this.ubicacion_por_referencia = new HashSet<ubicacion_por_referencia>();
            this.ubicacion1 = new HashSet<ubicacion>();
            this.ubicacionesxbodega_fisica = new HashSet<ubicacionesxbodega_fisica>();
            this.ubicacionxestado_bloqueo = new HashSet<ubicacionxestado_bloqueo>();
            this.ubicacionxestado_fisico = new HashSet<ubicacionxestado_fisico>();
            this.ubicacionxgrupo_inventario = new HashSet<ubicacionxgrupo_inventario>();
        }
    
        public int cod_ubicacion { get; set; }
        public Nullable<int> cod_bodega { get; set; }
        public Nullable<bool> es_reservada { get; set; }
        public Nullable<int> cod_linea { get; set; }
        public string cod_manual { get; set; }
        public string nombre_ubicacion { get; set; }
        public Nullable<bool> es_ubicacion_contenedora { get; set; }
        public Nullable<int> unidades_codigo_hija { get; set; }
        public Nullable<int> codigo_ubicacion_contenedora { get; set; }
        public Nullable<bool> controla_limite { get; set; }
        public Nullable<bool> lleno_total { get; set; }
        public Nullable<int> porcentaje_lleno { get; set; }
        public Nullable<double> largo { get; set; }
        public Nullable<double> ancho { get; set; }
        public Nullable<double> alto { get; set; }
        public Nullable<int> cod_unidad_medida { get; set; }
        public Nullable<double> peso_maximo { get; set; }
        public Nullable<int> cod_unidad_peso { get; set; }
        public Nullable<int> fila_relativa { get; set; }
        public Nullable<int> columna_relativa { get; set; }
        public Nullable<int> nivel_relativo { get; set; }
        public Nullable<double> x_relativo { get; set; }
        public Nullable<double> y_relativo { get; set; }
        public Nullable<double> z_relativo { get; set; }
        public bool es_abastecimiento { get; set; }
        public bool permite_niveles { get; set; }
        public bool es_frente { get; set; }
        public bool es_fondo { get; set; }
        public Nullable<int> ocupada { get; set; }
        public Nullable<bool> ind_1 { get; set; }
        public Nullable<bool> ind_2 { get; set; }
        public Nullable<bool> ind_3 { get; set; }
        public Nullable<bool> combina_hijas { get; set; }
    
        public virtual bodega bodega { get; set; }
        public virtual linea linea { get; set; }
        public virtual ICollection<ubicacion_por_referencia> ubicacion_por_referencia { get; set; }
        public virtual ICollection<ubicacion> ubicacion1 { get; set; }
        public virtual ubicacion ubicacion2 { get; set; }
        public virtual ICollection<ubicacionesxbodega_fisica> ubicacionesxbodega_fisica { get; set; }
        public virtual ICollection<ubicacionxestado_bloqueo> ubicacionxestado_bloqueo { get; set; }
        public virtual ICollection<ubicacionxestado_fisico> ubicacionxestado_fisico { get; set; }
        public virtual ICollection<ubicacionxgrupo_inventario> ubicacionxgrupo_inventario { get; set; }
    }
}
