//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class unidad_tiempo
    {
        public int cod_unidad_tiempo { get; set; }
        public string descripcion_unidad_tiempo { get; set; }
        public double factor_conversion { get; set; }
    }
}
