//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.adjunto_contrato_suministro = new HashSet<adjunto_contrato_suministro>();
            this.adjunto_contrato_suministro1 = new HashSet<adjunto_contrato_suministro>();
            this.adjunto_contrato_suministro2 = new HashSet<adjunto_contrato_suministro>();
            this.anuncio = new HashSet<anuncio>();
            this.archivo_template_revision_equipo = new HashSet<archivo_template_revision_equipo>();
            this.asistente_capacitacion = new HashSet<asistente_capacitacion>();
            this.asistentexsession = new HashSet<asistentexsession>();
            this.capacitacion = new HashSet<capacitacion>();
            this.cgq_layout_pivote = new HashSet<cgq_layout_pivote>();
            this.cgq_parametrosquery_ultimo_valor = new HashSet<cgq_parametrosquery_ultimo_valor>();
            this.cgq_queryxusuario = new HashSet<cgq_queryxusuario>();
            this.contrato_consumo = new HashSet<contrato_consumo>();
            this.contrato_consumo1 = new HashSet<contrato_consumo>();
            this.contratos_suministro = new HashSet<contratos_suministro>();
            this.control_calidad = new HashSet<control_calidad>();
            this.control_calidad1 = new HashSet<control_calidad>();
            this.control_calidad2 = new HashSet<control_calidad>();
            this.control_calidad3 = new HashSet<control_calidad>();
            this.control_calidad4 = new HashSet<control_calidad>();
            this.control_calidad5 = new HashSet<control_calidad>();
            this.control_calidad6 = new HashSet<control_calidad>();
            this.control_calidad7 = new HashSet<control_calidad>();
            this.detalle_movimiento = new HashSet<detalle_movimiento>();
            this.detalle_movimiento1 = new HashSet<detalle_movimiento>();
            this.estado_movimientoxusuario = new HashSet<estado_movimientoxusuario>();
            this.existencia = new HashSet<existencia>();
            this.funcionalidad_usuario = new HashSet<funcionalidad_usuario>();
            this.grupousuario_usuario = new HashSet<grupousuario_usuario>();
            this.lineasxusuario = new HashSet<lineasxusuario>();
            this.log_cambios_estado_contratos_suministro = new HashSet<log_cambios_estado_contratos_suministro>();
            this.logcambia_estado = new HashSet<logcambia_estado>();
            this.moduloseguridad_usuario = new HashSet<moduloseguridad_usuario>();
            this.movimiento = new HashSet<movimiento>();
            this.movimiento1 = new HashSet<movimiento>();
            this.movimiento2 = new HashSet<movimiento>();
            this.movimiento3 = new HashSet<movimiento>();
            this.movimiento4 = new HashSet<movimiento>();
            this.movimiento5 = new HashSet<movimiento>();
            this.notificacion_estado_copia_usuario = new HashSet<notificacion_estado_copia_usuario>();
            this.novedad_movimiento = new HashSet<novedad_movimiento>();
            this.novedad_movimiento1 = new HashSet<novedad_movimiento>();
            this.observicionesxseguimiento_control_calidad = new HashSet<observicionesxseguimiento_control_calidad>();
            this.pendiente_tarea = new HashSet<pendiente_tarea>();
            this.responsable_proceso = new HashSet<responsable_proceso>();
            this.revision_equipos = new HashSet<revision_equipos>();
            this.revision_equipos1 = new HashSet<revision_equipos>();
            this.revision_equipos2 = new HashSet<revision_equipos>();
            this.revision_equipos3 = new HashSet<revision_equipos>();
            this.solicitud_general = new HashSet<solicitud_general>();
            this.solicitud_general1 = new HashSet<solicitud_general>();
            this.solicitud_general2 = new HashSet<solicitud_general>();
            this.tarea_calendario = new HashSet<tarea_calendario>();
            this.tarea_calendario1 = new HashSet<tarea_calendario>();
            this.template_revison_equipo = new HashSet<template_revison_equipo>();
        }
    
        public int cod_usuario { get; set; }
        public string login { get; set; }
        public string nombre { get; set; }
        public string documento { get; set; }
        public Nullable<int> cod_tipo_documento { get; set; }
        public string password { get; set; }
        public Nullable<bool> es_bloqueado { get; set; }
        public string correo { get; set; }
        public Nullable<int> intentos { get; set; }
        public Nullable<System.DateTime> fecha_cambio_password { get; set; }
    
        public virtual ICollection<adjunto_contrato_suministro> adjunto_contrato_suministro { get; set; }
        public virtual ICollection<adjunto_contrato_suministro> adjunto_contrato_suministro1 { get; set; }
        public virtual ICollection<adjunto_contrato_suministro> adjunto_contrato_suministro2 { get; set; }
        public virtual ICollection<anuncio> anuncio { get; set; }
        public virtual ICollection<archivo_template_revision_equipo> archivo_template_revision_equipo { get; set; }
        public virtual ICollection<asistente_capacitacion> asistente_capacitacion { get; set; }
        public virtual ICollection<asistentexsession> asistentexsession { get; set; }
        public virtual ICollection<capacitacion> capacitacion { get; set; }
        public virtual ICollection<cgq_layout_pivote> cgq_layout_pivote { get; set; }
        public virtual ICollection<cgq_parametrosquery_ultimo_valor> cgq_parametrosquery_ultimo_valor { get; set; }
        public virtual ICollection<cgq_queryxusuario> cgq_queryxusuario { get; set; }
        public virtual ICollection<contrato_consumo> contrato_consumo { get; set; }
        public virtual ICollection<contrato_consumo> contrato_consumo1 { get; set; }
        public virtual ICollection<contratos_suministro> contratos_suministro { get; set; }
        public virtual ICollection<control_calidad> control_calidad { get; set; }
        public virtual ICollection<control_calidad> control_calidad1 { get; set; }
        public virtual ICollection<control_calidad> control_calidad2 { get; set; }
        public virtual ICollection<control_calidad> control_calidad3 { get; set; }
        public virtual ICollection<control_calidad> control_calidad4 { get; set; }
        public virtual ICollection<control_calidad> control_calidad5 { get; set; }
        public virtual ICollection<control_calidad> control_calidad6 { get; set; }
        public virtual ICollection<control_calidad> control_calidad7 { get; set; }
        public virtual ICollection<detalle_movimiento> detalle_movimiento { get; set; }
        public virtual ICollection<detalle_movimiento> detalle_movimiento1 { get; set; }
        public virtual ICollection<estado_movimientoxusuario> estado_movimientoxusuario { get; set; }
        public virtual ICollection<existencia> existencia { get; set; }
        public virtual ICollection<funcionalidad_usuario> funcionalidad_usuario { get; set; }
        public virtual ICollection<grupousuario_usuario> grupousuario_usuario { get; set; }
        public virtual ICollection<lineasxusuario> lineasxusuario { get; set; }
        public virtual ICollection<log_cambios_estado_contratos_suministro> log_cambios_estado_contratos_suministro { get; set; }
        public virtual ICollection<logcambia_estado> logcambia_estado { get; set; }
        public virtual ICollection<moduloseguridad_usuario> moduloseguridad_usuario { get; set; }
        public virtual ICollection<movimiento> movimiento { get; set; }
        public virtual ICollection<movimiento> movimiento1 { get; set; }
        public virtual ICollection<movimiento> movimiento2 { get; set; }
        public virtual ICollection<movimiento> movimiento3 { get; set; }
        public virtual ICollection<movimiento> movimiento4 { get; set; }
        public virtual ICollection<movimiento> movimiento5 { get; set; }
        public virtual ICollection<notificacion_estado_copia_usuario> notificacion_estado_copia_usuario { get; set; }
        public virtual ICollection<novedad_movimiento> novedad_movimiento { get; set; }
        public virtual ICollection<novedad_movimiento> novedad_movimiento1 { get; set; }
        public virtual ICollection<observicionesxseguimiento_control_calidad> observicionesxseguimiento_control_calidad { get; set; }
        public virtual ICollection<pendiente_tarea> pendiente_tarea { get; set; }
        public virtual ICollection<responsable_proceso> responsable_proceso { get; set; }
        public virtual ICollection<revision_equipos> revision_equipos { get; set; }
        public virtual ICollection<revision_equipos> revision_equipos1 { get; set; }
        public virtual ICollection<revision_equipos> revision_equipos2 { get; set; }
        public virtual ICollection<revision_equipos> revision_equipos3 { get; set; }
        public virtual ICollection<solicitud_general> solicitud_general { get; set; }
        public virtual ICollection<solicitud_general> solicitud_general1 { get; set; }
        public virtual ICollection<solicitud_general> solicitud_general2 { get; set; }
        public virtual ICollection<tarea_calendario> tarea_calendario { get; set; }
        public virtual ICollection<tarea_calendario> tarea_calendario1 { get; set; }
        public virtual ICollection<template_revison_equipo> template_revison_equipo { get; set; }
        public virtual tipo_documento tipo_documento { get; set; }
    }
}
