//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class variables_medicionxorden_servicio
    {
        public int cod_variables_medicionxorden_servicio { get; set; }
        public Nullable<int> codOrdenServicio { get; set; }
        public Nullable<decimal> resultado_variable { get; set; }
        public Nullable<int> cod_sub_variable_medicion { get; set; }
        public Nullable<bool> relizado_por_equipo { get; set; }
    
        public virtual ordenServicio ordenServicio { get; set; }
    }
}
