//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vistaSucursal
    {
        public string nitCliente { get; set; }
        public string codSucursal { get; set; }
        public string nombreSucursal { get; set; }
        public string Direccion { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string codContacto { get; set; }
        public string nombrePais { get; set; }
        public string NombreDepartamento { get; set; }
        public string nombreCiudad { get; set; }
    }
}
