//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class wcg_smtp_adjuntos
    {
        public int cod_wcg_smtp_adjuntos { get; set; }
        public int cod_wcg_smtp_email { get; set; }
        public string nombre_adjunto { get; set; }
        public byte[] archivo { get; set; }
    
        public virtual wcg_smtp_email wcg_smtp_email { get; set; }
    }
}
