//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class wcg_virtual_grp
    {
        public wcg_virtual_grp()
        {
            this.wcg_virtual_field = new HashSet<wcg_virtual_field>();
        }
    
        public int cod_wcg_virtual_grp { get; set; }
        public int cod_wcg_virtual_tab { get; set; }
        public string texto { get; set; }
        public Nullable<int> ancho_fijo { get; set; }
        public Nullable<int> largo_fijo { get; set; }
        public Nullable<int> orden { get; set; }
        public Nullable<int> columna { get; set; }
    
        public virtual ICollection<wcg_virtual_field> wcg_virtual_field { get; set; }
        public virtual wcg_virtual_tab wcg_virtual_tab { get; set; }
    }
}
