//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spxBussines.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class wcg_virtual_field
    {
        public int cod_wcg_virtual_field { get; set; }
        public int cod_wcg_virtual_grp { get; set; }
        public Nullable<int> cod_wcg_mapping { get; set; }
        public Nullable<int> orden { get; set; }
        public Nullable<bool> obligatorio { get; set; }
        public Nullable<bool> editable { get; set; }
        public Nullable<int> ancho_fijo { get; set; }
        public Nullable<int> largo_fijo { get; set; }
        public Nullable<bool> cargar_fecha_now { get; set; }
        public Nullable<bool> cheched_load { get; set; }
        public Nullable<int> cod_combo_padre { get; set; }
        public string link_combo_padre { get; set; }
        public Nullable<int> cod_frm_virtual_detalle { get; set; }
        public string sentencia_detalle { get; set; }
        public string label_detalle { get; set; }
        public Nullable<bool> ocultar_agregar { get; set; }
        public Nullable<bool> ocultar_editar { get; set; }
        public Nullable<bool> ocultar_eliminar { get; set; }
        public string frm_virtual_real { get; set; }
        public string filtro_obligado_movimiento { get; set; }
        public string filtro_obligado_movimiento_campo { get; set; }
    
        public virtual wcg_mapping wcg_mapping { get; set; }
        public virtual wcg_virtual_grp wcg_virtual_grp { get; set; }
    }
}
